export const EXPIRY_ESTIMATES = {
  "milk": { days: 7, cat: "Dairy" }, "whole milk": { days: 7, cat: "Dairy" },
  "oat milk": { days: 10, cat: "Dairy" }, "almond milk": { days: 10, cat: "Dairy" },
  "yogurt": { days: 14, cat: "Dairy" }, "greek yogurt": { days: 14, cat: "Dairy" },
  "butter": { days: 30, cat: "Dairy" }, "cheese": { days: 21, cat: "Dairy" },
  "cream cheese": { days: 14, cat: "Dairy" }, "sour cream": { days: 14, cat: "Dairy" },
  "eggs": { days: 21, cat: "Dairy" }, "heavy cream": { days: 10, cat: "Dairy" },
  "chicken": { days: 3, cat: "Meat" }, "chicken breast": { days: 3, cat: "Meat" },
  "ground beef": { days: 3, cat: "Meat" }, "steak": { days: 4, cat: "Meat" },
  "pork": { days: 4, cat: "Meat" }, "bacon": { days: 7, cat: "Meat" },
  "sausage": { days: 5, cat: "Meat" }, "ham": { days: 5, cat: "Meat" },
  "turkey": { days: 3, cat: "Meat" }, "ground turkey": { days: 3, cat: "Meat" },
  "salmon": { days: 2, cat: "Seafood" }, "shrimp": { days: 2, cat: "Seafood" },
  "fish": { days: 2, cat: "Seafood" }, "tuna": { days: 2, cat: "Seafood" },
  "lettuce": { days: 5, cat: "Produce" }, "spinach": { days: 5, cat: "Produce" },
  "kale": { days: 5, cat: "Produce" }, "arugula": { days: 4, cat: "Produce" },
  "tomatoes": { days: 7, cat: "Produce" }, "tomato": { days: 7, cat: "Produce" },
  "cucumber": { days: 7, cat: "Produce" }, "bell pepper": { days: 7, cat: "Produce" },
  "onion": { days: 30, cat: "Produce" }, "garlic": { days: 30, cat: "Produce" },
  "potato": { days: 21, cat: "Produce" }, "potatoes": { days: 21, cat: "Produce" },
  "sweet potato": { days: 14, cat: "Produce" },
  "carrot": { days: 21, cat: "Produce" }, "carrots": { days: 21, cat: "Produce" },
  "celery": { days: 14, cat: "Produce" }, "broccoli": { days: 5, cat: "Produce" },
  "cauliflower": { days: 7, cat: "Produce" }, "mushrooms": { days: 5, cat: "Produce" },
  "avocado": { days: 4, cat: "Produce" }, "banana": { days: 5, cat: "Produce" },
  "bananas": { days: 5, cat: "Produce" }, "apple": { days: 21, cat: "Produce" },
  "apples": { days: 21, cat: "Produce" }, "orange": { days: 14, cat: "Produce" },
  "oranges": { days: 14, cat: "Produce" }, "lemon": { days: 21, cat: "Produce" },
  "lemons": { days: 21, cat: "Produce" }, "lime": { days: 14, cat: "Produce" },
  "berries": { days: 4, cat: "Produce" }, "strawberries": { days: 4, cat: "Produce" },
  "blueberries": { days: 7, cat: "Produce" }, "raspberries": { days: 3, cat: "Produce" },
  "grapes": { days: 7, cat: "Produce" }, "mango": { days: 5, cat: "Produce" },
  "cilantro": { days: 5, cat: "Produce" }, "basil": { days: 5, cat: "Produce" },
  "parsley": { days: 7, cat: "Produce" }, "green onion": { days: 7, cat: "Produce" },
  "ginger": { days: 21, cat: "Produce" }, "jalapeño": { days: 14, cat: "Produce" },
  "corn": { days: 5, cat: "Produce" }, "zucchini": { days: 7, cat: "Produce" },
  "bread": { days: 5, cat: "Bakery" }, "bagels": { days: 5, cat: "Bakery" },
  "tortillas": { days: 14, cat: "Bakery" }, "pita": { days: 7, cat: "Bakery" },
  "croissants": { days: 3, cat: "Bakery" }, "muffins": { days: 4, cat: "Bakery" },
  "rice": { days: 365, cat: "Grains" }, "pasta": { days: 365, cat: "Grains" },
  "oats": { days: 180, cat: "Grains" }, "quinoa": { days: 365, cat: "Grains" },
  "cereal": { days: 180, cat: "Grains" },
  "ketchup": { days: 180, cat: "Condiments" }, "mustard": { days: 365, cat: "Condiments" },
  "mayo": { days: 60, cat: "Condiments" }, "mayonnaise": { days: 60, cat: "Condiments" },
  "soy sauce": { days: 365, cat: "Condiments" }, "hot sauce": { days: 365, cat: "Condiments" },
  "salsa": { days: 14, cat: "Condiments" }, "hummus": { days: 10, cat: "Condiments" },
  "peanut butter": { days: 90, cat: "Condiments" }, "jam": { days: 90, cat: "Condiments" },
  "juice": { days: 7, cat: "Beverages" }, "orange juice": { days: 7, cat: "Beverages" },
  "coffee": { days: 30, cat: "Beverages" }, "wine": { days: 5, cat: "Beverages" },
  "beer": { days: 90, cat: "Beverages" }, "soda": { days: 180, cat: "Beverages" },
  "frozen pizza": { days: 180, cat: "Frozen" }, "ice cream": { days: 60, cat: "Frozen" },
  "frozen vegetables": { days: 240, cat: "Frozen" }, "frozen fruit": { days: 240, cat: "Frozen" },
  "chips": { days: 60, cat: "Snacks" }, "crackers": { days: 60, cat: "Snacks" },
  "nuts": { days: 90, cat: "Snacks" }, "chocolate": { days: 120, cat: "Snacks" },
  "cookies": { days: 14, cat: "Snacks" }, "granola bars": { days: 180, cat: "Snacks" },
  "tofu": { days: 7, cat: "Produce" }, "tempeh": { days: 10, cat: "Produce" },
};

export const QUICK_ITEMS = [
  "Milk", "Eggs", "Bread", "Butter", "Cheese", "Chicken", "Rice", "Bananas",
  "Yogurt", "Spinach", "Tomatoes", "Onion", "Garlic", "Pasta", "Salmon",
  "Avocado", "Apples", "Carrots", "Broccoli", "Ground Beef",
];
