// ─── Massive food → emoji map (300+ entries) ───
// Matched case-insensitively via getFoodEmoji()

export const FOOD_EMOJI = {
  // ── Fruits ──
  apple: "🍎", "green apple": "🍏", banana: "🍌", orange: "🍊",
  lemon: "🍋", lime: "🍋", grape: "🍇", grapes: "🍇",
  strawberry: "🍓", strawberries: "🍓", blueberry: "🫐", blueberries: "🫐",
  raspberry: "🫐", raspberries: "🫐", blackberry: "🫐", blackberries: "🫐",
  cranberry: "🫐", cranberries: "🫐",
  cherry: "🍒", cherries: "🍒", peach: "🍑", peaches: "🍑",
  pear: "🍐", pears: "🍐", plum: "🍑", plums: "🍑",
  watermelon: "🍉", cantaloupe: "🍈", honeydew: "🍈", melon: "🍈",
  mango: "🥭", mangoes: "🥭", kiwi: "🥝",
  pineapple: "🍍", coconut: "🥥", avocado: "🥑",
  pomegranate: "🍎", fig: "🍇", "passion fruit": "🍑",
  papaya: "🥭", guava: "🍐", "dragon fruit": "🍑",
  lychee: "🍑", "star fruit": "⭐", persimmon: "🍑",
  apricot: "🍑", apricots: "🍑", nectarine: "🍑",
  tangerine: "🍊", clementine: "🍊", mandarin: "🍊", grapefruit: "🍊",
  "dried fruit": "🍇", raisins: "🍇", dates: "🍇", prunes: "🍇",

  // ── Vegetables ──
  tomato: "🍅", tomatoes: "🍅", "cherry tomato": "🍅", "cherry tomatoes": "🍅",
  corn: "🌽", "corn on the cob": "🌽",
  pepper: "🌶️", peppers: "🌶️", "bell pepper": "🫑", "bell peppers": "🫑",
  "jalapeño": "🌶️", jalapeno: "🌶️", "habanero": "🌶️", "chili pepper": "🌶️",
  "hot pepper": "🌶️", "serrano": "🌶️", "poblano": "🫑",
  broccoli: "🥦", "broccoli florets": "🥦",
  lettuce: "🥬", "romaine": "🥬", "iceberg lettuce": "🥬",
  spinach: "🥬", kale: "🥬", arugula: "🥬", "swiss chard": "🥬",
  "collard greens": "🥬", "bok choy": "🥬", cabbage: "🥬", "red cabbage": "🥬",
  "brussels sprouts": "🥬", "brussels sprout": "🥬",
  cucumber: "🥒", cucumbers: "🥒", pickle: "🥒", pickles: "🥒", zucchini: "🥒",
  carrot: "🥕", carrots: "🥕", "baby carrots": "🥕",
  potato: "🥔", potatoes: "🥔", "russet potato": "🥔", "yukon gold": "🥔",
  "sweet potato": "🍠", "sweet potatoes": "🍠", yam: "🍠",
  onion: "🧅", onions: "🧅", "red onion": "🧅", "green onion": "🧅",
  "spring onion": "🧅", scallion: "🧅", scallions: "🧅", shallot: "🧅",
  garlic: "🧄", "garlic cloves": "🧄",
  mushroom: "🍄", mushrooms: "🍄", "shiitake": "🍄", "portobello": "🍄",
  "cremini": "🍄", "button mushroom": "🍄",
  ginger: "🫚", "fresh ginger": "🫚", turmeric: "🫚",
  celery: "🥬", "celery sticks": "🥬",
  asparagus: "🥦", "green beans": "🫘", "snap peas": "🫛", "snow peas": "🫛",
  peas: "🫛", "edamame": "🫛",
  "artichoke": "🥬", eggplant: "🍆", "aubergine": "🍆",
  beet: "🟣", beets: "🟣", beetroot: "🟣",
  radish: "🥕", turnip: "🥔", parsnip: "🥕", rutabaga: "🥔",
  cauliflower: "🥦", "cauliflower florets": "🥦",
  squash: "🎃", "butternut squash": "🎃", "acorn squash": "🎃",
  pumpkin: "🎃",
  "mixed greens": "🥬", "salad mix": "🥗", "coleslaw": "🥬",
  "bean sprouts": "🌱", sprouts: "🌱", microgreens: "🌱",
  herbs: "🌿", basil: "🌿", cilantro: "🌿", parsley: "🌿", mint: "🌿",
  dill: "🌿", rosemary: "🌿", thyme: "🌿", oregano: "🌿", sage: "🌿",
  chives: "🌿", "fresh herbs": "🌿", "bay leaves": "🌿",

  // ── Proteins ──
  egg: "🥚", eggs: "🥚", "egg whites": "🥚", "hard boiled egg": "🥚",
  chicken: "🍗", "chicken breast": "🍗", "chicken thigh": "🍗",
  "chicken wing": "🍗", "chicken wings": "🍗", "chicken tender": "🍗",
  "chicken leg": "🍗", "rotisserie chicken": "🍗", "grilled chicken": "🍗",
  turkey: "🍗", "turkey breast": "🍗", "ground turkey": "🍗", "turkey bacon": "🥓",
  "deli turkey": "🍗",
  steak: "🥩", beef: "🥩", "ground beef": "🥩", "beef stew": "🍲",
  "sirloin": "🥩", "ribeye": "🥩", "filet mignon": "🥩", "flank steak": "🥩",
  "chuck roast": "🥩", "brisket": "🥩", "corned beef": "🥩",
  pork: "🥩", "pork chop": "🥩", "pork loin": "🥩", "pork tenderloin": "🥩",
  "pulled pork": "🥩", "ground pork": "🥩", "pork belly": "🥩",
  bacon: "🥓", "turkey bacon": "🥓", "canadian bacon": "🥓",
  ham: "🍖", "deli ham": "🍖", prosciutto: "🍖", pancetta: "🥓",
  sausage: "🌭", "italian sausage": "🌭", bratwurst: "🌭",
  "breakfast sausage": "🌭", chorizo: "🌭",
  lamb: "🥩", "lamb chop": "🥩", "ground lamb": "🥩",
  veal: "🥩", bison: "🥩", venison: "🥩", duck: "🍗",
  pepperoni: "🍕", salami: "🥩", "deli meat": "🥩", "lunch meat": "🥩",

  // ── Seafood ──
  fish: "🐟", salmon: "🐟", "smoked salmon": "🐟", "salmon fillet": "🐟",
  tuna: "🐟", "canned tuna": "🐟", "ahi tuna": "🐟",
  cod: "🐟", tilapia: "🐟", halibut: "🐟", "sea bass": "🐟",
  trout: "🐟", catfish: "🐟", mahi: "🐟", swordfish: "🐟",
  sardine: "🐟", sardines: "🐟", anchovy: "🐟", anchovies: "🐟",
  shrimp: "🦐", prawns: "🦐", "jumbo shrimp": "🦐",
  crab: "🦀", "crab meat": "🦀", "crab cake": "🦀",
  lobster: "🦞", "lobster tail": "🦞",
  clam: "🦪", clams: "🦪", mussel: "🦪", mussels: "🦪",
  oyster: "🦪", oysters: "🦪", scallop: "🦪", scallops: "🦪",
  calamari: "🦑", squid: "🦑", octopus: "🐙",

  // ── Dairy ──
  milk: "🥛", "whole milk": "🥛", "skim milk": "🥛", "2% milk": "🥛",
  "oat milk": "🥛", "almond milk": "🥛", "soy milk": "🥛",
  "coconut milk": "🥛", "cashew milk": "🥛", "half and half": "🥛",
  cream: "🥛", "heavy cream": "🥛", "whipping cream": "🥛",
  "coffee creamer": "🥛",
  cheese: "🧀", cheddar: "🧀", mozzarella: "🧀", parmesan: "🧀",
  "swiss cheese": "🧀", provolone: "🧀", brie: "🧀", gouda: "🧀",
  feta: "🧀", "goat cheese": "🧀", ricotta: "🧀", "blue cheese": "🧀",
  "pepper jack": "🧀", "colby jack": "🧀", "monterey jack": "🧀",
  "cream cheese": "🧀", "cottage cheese": "🧀", "string cheese": "🧀",
  "shredded cheese": "🧀", "sliced cheese": "🧀", "cheese stick": "🧀",
  butter: "🧈", "unsalted butter": "🧈", margarine: "🧈", ghee: "🧈",
  yogurt: "🥛", "greek yogurt": "🥛", "yogurt cup": "🥛", kefir: "🥛",
  "sour cream": "🥛", "whipped cream": "🥛",
  "ice cream": "🍦", gelato: "🍦", sorbet: "🍦", "frozen yogurt": "🍦",

  // ── Grains & Bread ──
  bread: "🍞", "white bread": "🍞", "wheat bread": "🍞", "sourdough": "🍞",
  "rye bread": "🍞", "pumpernickel": "🍞", "multigrain": "🍞",
  bagel: "🥯", bagels: "🥯", "everything bagel": "🥯",
  croissant: "🥐", pretzel: "🥨", muffin: "🧁", scone: "🧁",
  "english muffin": "🍞", "pita": "🫓", "pita bread": "🫓", flatbread: "🫓",
  "naan": "🫓", tortilla: "🫓", "flour tortilla": "🫓", "corn tortilla": "🫓",
  wrap: "🫓", bun: "🍞", "hamburger bun": "🍞", "hot dog bun": "🍞",
  roll: "🍞", "dinner roll": "🍞", biscuit: "🍞",
  rice: "🍚", "white rice": "🍚", "brown rice": "🍚", "jasmine rice": "🍚",
  "basmati rice": "🍚", "fried rice": "🍚", "rice cake": "🍚",
  quinoa: "🌾", couscous: "🌾", barley: "🌾", bulgur: "🌾", farro: "🌾",
  pasta: "🍝", spaghetti: "🍝", penne: "🍝", rigatoni: "🍝",
  linguine: "🍝", fettuccine: "🍝", macaroni: "🍝", "mac and cheese": "🍝",
  fusilli: "🍝", orzo: "🍝", "angel hair": "🍝", rotini: "🍝",
  noodle: "🍜", noodles: "🍜", ramen: "🍜", "ramen noodles": "🍜",
  udon: "🍜", soba: "🍜", "rice noodles": "🍜", "egg noodles": "🍜",
  oats: "🌾", oatmeal: "🥣", "rolled oats": "🌾", granola: "🥣",
  cereal: "🥣", "corn flakes": "🥣",
  flour: "🌾", "all purpose flour": "🌾", "bread flour": "🌾",
  "almond flour": "🌾", "coconut flour": "🌾",
  "pancake mix": "🥞", "waffle mix": "🧇",
  cracker: "🍘", crackers: "🍘", "graham cracker": "🍘",
  breadcrumbs: "🍞", panko: "🍞", croutons: "🍞",

  // ── Prepared Foods ──
  pizza: "🍕", "frozen pizza": "🍕",
  burger: "🍔", hamburger: "🍔", cheeseburger: "🍔",
  sandwich: "🥪", "grilled cheese": "🥪", sub: "🥪",
  taco: "🌮", tacos: "🌮", burrito: "🌯", burritos: "🌯",
  quesadilla: "🌯", enchilada: "🌯",
  "hot dog": "🌭", fries: "🍟", "french fries": "🍟", "tater tots": "🍟",
  nuggets: "🍗", "chicken nuggets": "🍗", "fish sticks": "🐟",
  soup: "🍲", stew: "🍲", chili: "🍲", "chicken soup": "🍲",
  curry: "🍛", "chicken curry": "🍛", "thai curry": "🍛",
  salad: "🥗", "caesar salad": "🥗", "greek salad": "🥗",
  sushi: "🍣", "sushi roll": "🍣", sashimi: "🍣",
  dumpling: "🥟", dumplings: "🥟", gyoza: "🥟",
  "spring roll": "🥟", "egg roll": "🥟",
  waffle: "🧇", waffles: "🧇", pancake: "🥞", pancakes: "🥞",
  "french toast": "🍞", crepe: "🥞",
  "fried rice": "🍚", "stir fry": "🍳", omelette: "🍳", omelet: "🍳",
  "scrambled eggs": "🍳", "fried egg": "🍳",
  hummus: "🫘", guacamole: "🥑", salsa: "🫙",

  // ── Snacks ──
  popcorn: "🍿", chip: "🍿", chips: "🍿", "potato chips": "🍿",
  "tortilla chips": "🍿", nachos: "🍿", pretzel: "🥨",
  "trail mix": "🥜", "mixed nuts": "🥜", cashew: "🥜", cashews: "🥜",
  walnut: "🥜", walnuts: "🥜", pecan: "🥜", pecans: "🥜",
  pistachio: "🥜", pistachios: "🥜", "sunflower seeds": "🌻",
  "pumpkin seeds": "🎃", "chia seeds": "🌱", "flax seeds": "🌱",
  "beef jerky": "🥩", jerky: "🥩",
  "protein bar": "🍫", "granola bar": "🍫", "energy bar": "🍫",
  "rice cake": "🍘", "fruit snacks": "🍬",

  // ── Sweets & Baking ──
  cake: "🍰", "birthday cake": "🎂", cheesecake: "🍰",
  cookie: "🍪", cookies: "🍪", brownie: "🍫", brownies: "🍫",
  donut: "🍩", donuts: "🍩", doughnut: "🍩",
  chocolate: "🍫", "dark chocolate": "🍫", "milk chocolate": "🍫",
  "chocolate chips": "🍫", "cocoa powder": "🍫",
  candy: "🍬", "gummy bears": "🍬", "jelly beans": "🍬",
  pie: "🥧", "apple pie": "🥧", "pumpkin pie": "🥧",
  cupcake: "🧁", cupcakes: "🧁",
  "ice cream": "🍦", "ice cream sandwich": "🍦", popsicle: "🍦",
  sugar: "🍬", "brown sugar": "🍬", "powdered sugar": "🍬",
  "maple syrup": "🍁", syrup: "🍁", molasses: "🍯",
  "vanilla extract": "🧁", "baking soda": "🧂", "baking powder": "🧂",
  sprinkles: "🍬", frosting: "🧁", icing: "🧁",
  "whipped topping": "🍦", "cool whip": "🍦",

  // ── Beverages ──
  coffee: "☕", "iced coffee": "☕", espresso: "☕", latte: "☕",
  "cold brew": "☕", cappuccino: "☕", "coffee beans": "☕", "coffee grounds": "☕",
  tea: "🍵", "green tea": "🍵", "black tea": "🍵", "herbal tea": "🍵",
  "iced tea": "🍵", matcha: "🍵", "chai tea": "🍵",
  juice: "🧃", "orange juice": "🧃", "apple juice": "🧃",
  "cranberry juice": "🧃", "grape juice": "🧃", "tomato juice": "🧃",
  lemonade: "🍋", "fruit punch": "🧃",
  water: "💧", "sparkling water": "💧", "coconut water": "💧",
  soda: "🥤", "coca cola": "🥤", coke: "🥤", sprite: "🥤",
  "ginger ale": "🥤", "root beer": "🥤", "dr pepper": "🥤",
  "energy drink": "🥤", "red bull": "🥤", gatorade: "🥤",
  "sports drink": "🥤",
  wine: "🍷", "red wine": "🍷", "white wine": "🍷", champagne: "🥂",
  beer: "🍺", "craft beer": "🍺", ipa: "🍺", lager: "🍺",
  "hard seltzer": "🥤", "hard cider": "🍺",
  cocktail: "🍸", margarita: "🍸", martini: "🍸",
  whiskey: "🥃", bourbon: "🥃", vodka: "🍸", rum: "🍹", tequila: "🍸",
  sake: "🍶", kombucha: "🍵",
  smoothie: "🥤", "protein shake": "🥤", milkshake: "🥤",

  // ── Condiments & Sauces ──
  ketchup: "🫙", mustard: "🫙", "dijon mustard": "🫙",
  mayonnaise: "🫙", mayo: "🫙",
  "hot sauce": "🌶️", "sriracha": "🌶️", "tabasco": "🌶️",
  "bbq sauce": "🫙", "barbecue sauce": "🫙",
  "soy sauce": "🫙", "teriyaki sauce": "🫙", "fish sauce": "🫙",
  "worcestershire": "🫙", "hoisin sauce": "🫙",
  "tomato sauce": "🍅", "marinara": "🍅", "pasta sauce": "🍅",
  "alfredo sauce": "🫙", "pesto": "🌿",
  "ranch dressing": "🫙", "italian dressing": "🫙", "balsamic": "🫙",
  "salad dressing": "🫙", vinaigrette: "🫙",
  vinegar: "🫙", "apple cider vinegar": "🫙", "balsamic vinegar": "🫙",
  "rice vinegar": "🫙", "red wine vinegar": "🫙",
  oil: "🫒", "olive oil": "🫒", "vegetable oil": "🫒", "coconut oil": "🫒",
  "sesame oil": "🫒", "avocado oil": "🫒", "canola oil": "🫒",
  salt: "🧂", "sea salt": "🧂", "kosher salt": "🧂",
  "black pepper": "🧂", "ground pepper": "🧂",
  "tomato paste": "🍅", "tomato puree": "🍅",
  honey: "🍯", "raw honey": "🍯",
  jam: "🫙", jelly: "🫙", marmalade: "🫙", preserves: "🫙",
  "peanut butter": "🥜", "almond butter": "🥜",
  nutella: "🍫", "chocolate spread": "🍫",
  relish: "🫙", chutney: "🫙", "cranberry sauce": "🫙",
  "cream of mushroom": "🍄", "cream of chicken": "🍗",
  broth: "🍲", "chicken broth": "🍲", "beef broth": "🍲",
  "vegetable broth": "🍲", stock: "🍲", bouillon: "🍲",

  // ── Legumes & Beans ──
  bean: "🫘", beans: "🫘", "black bean": "🫘", "black beans": "🫘",
  "kidney beans": "🫘", "pinto beans": "🫘", "navy beans": "🫘",
  "cannellini beans": "🫘", "garbanzo beans": "🫘", "refried beans": "🫘",
  lentil: "🫘", lentils: "🫘", "red lentils": "🫘", "green lentils": "🫘",
  chickpea: "🫘", chickpeas: "🫘",
  "baked beans": "🫘", "chili beans": "🫘",

  // ── Tofu & Plant-Based ──
  tofu: "🧊", tempeh: "🧊", seitan: "🧊",
  "beyond meat": "🥩", "impossible burger": "🥩", "plant based": "🌱",
  "veggie burger": "🍔", "veggie patty": "🍔",

  // ── Frozen ──
  "frozen vegetables": "🧊", "frozen fruit": "🧊", "frozen berries": "🧊",
  "frozen peas": "🧊", "frozen corn": "🧊", "frozen spinach": "🧊",
  "frozen dinner": "🧊", "tv dinner": "🧊",
  "ice": "🧊", "ice cubes": "🧊",

  // ── Supplements & Health ──
  "protein powder": "🥛", "whey protein": "🥛", "casein": "🥛",
  creatine: "💊", supplement: "💊", vitamins: "💊", multivitamin: "💊",
  "fish oil": "💊", "probiotic": "💊", "collagen": "💊",
  "pre workout": "💊", "bcaa": "💊", electrolytes: "💊",

  // ── Miscellaneous ──
  "corn starch": "🌽", "yeast": "🍞", "gelatin": "🫙",
  "coconut flakes": "🥥", "shredded coconut": "🥥",
  "dried cranberries": "🫐", "dried apricots": "🍑",
  "sun dried tomatoes": "🍅",
  "capers": "🫒", "olives": "🫒", "green olives": "🫒", "black olives": "🫒",
  "pickled jalapeños": "🌶️", "sauerkraut": "🥬", kimchi: "🥬",
  "tortilla chips": "🍿", "pita chips": "🍿",
  "rice paper": "🍚", "wonton wrappers": "🥟",
  "canned corn": "🌽", "canned tomatoes": "🍅", "canned beans": "🫘",
  "canned soup": "🍲", "canned tuna": "🐟", "canned chicken": "🍗",
  "canned salmon": "🐟", "canned fruit": "🍑",
};

export const CATEGORY_FALLBACK = {
  Produce: "🥬", Dairy: "🧀", Meat: "🥩", Seafood: "🐟",
  Grains: "🌾", Frozen: "🧊", Condiments: "🫙", Beverages: "🥤",
  Snacks: "🍪", Bakery: "🍞", Leftovers: "🍲", Other: "🍽️",
};

export function getFoodEmoji(name, category) {
  const key = name.toLowerCase().trim();
  if (FOOD_EMOJI[key]) return FOOD_EMOJI[key];
  // Partial match
  for (const [k, v] of Object.entries(FOOD_EMOJI)) {
    if (key.includes(k) || k.includes(key)) return v;
  }
  // Singular/plural
  const singular = key.endsWith("s") ? key.slice(0, -1) : key;
  if (FOOD_EMOJI[singular]) return FOOD_EMOJI[singular];
  const plural = key + "s";
  if (FOOD_EMOJI[plural]) return FOOD_EMOJI[plural];
  return CATEGORY_FALLBACK[category] || "🍽️";
}
