import { RECIPES_BATCH_1 } from "./recipes1";
import { RECIPES_BATCH_2 } from "./recipes2";
import { RECIPES_BATCH_3 } from "./recipes3";

export const STORAGE_KEYS = {
  items: "ff2-items",
  meals: "ff2-meals",
  shopping: "ff2-shopping",
  favorites: "ff2-favorites",
  lowStock: "ff2-lowstock",
  staples: "ff2-staples",
  recipes: "ff2-recipes",
  recurring: "ff2-recurring",
  macroLog: "ff2-macrolog",
  macroGoals: "ff2-macrogoals",
  gymLog: "ff2-gymlog",
  bodyWeight: "ff2-bodyweight",
  userProfile: "ff2-userprofile",
};

export const DEFAULT_RECIPES = [
  // ─── QUICK & EASY (35) ───────────────────────────────────────────
  {
    id: "dr-pbj",
    name: "PB&J",
    ingredients: ["Bread", "Peanut Butter", "Jam"],
    calories: "350", protein: "12", time: "3 min",
    notes: "Classic. Toast the bread for next-level.",
  },
  {
    id: "dr-grilled-cheese",
    name: "Grilled Cheese",
    ingredients: ["Bread", "Butter", "Cheese"],
    calories: "400", protein: "14", time: "8 min",
    notes: "Low heat, be patient. Add tomato soup on the side.",
  },
  {
    id: "dr-quesadilla",
    name: "Quesadilla",
    ingredients: ["Tortilla", "Cheese", "Butter"],
    calories: "380", protein: "15", time: "7 min",
    notes: "Add chicken, beans, or veggies for a full meal.",
  },
  {
    id: "dr-egg-toast",
    name: "Egg on Toast",
    ingredients: ["Bread", "Eggs", "Butter", "Salt", "Pepper"],
    calories: "320", protein: "16", time: "5 min",
    notes: "Fried, scrambled, or poached — dealer's choice.",
  },
  {
    id: "dr-avocado-toast",
    name: "Avocado Toast",
    ingredients: ["Bread", "Avocado", "Salt", "Pepper"],
    calories: "300", protein: "7", time: "5 min",
    notes: "Add an egg on top, everything bagel seasoning, or hot sauce.",
  },
  {
    id: "dr-bagel-cc",
    name: "Bagel & Cream Cheese",
    ingredients: ["Bagel", "Cream Cheese"],
    calories: "350", protein: "10", time: "3 min",
    notes: "Toast the bagel. Everything bagels are the move.",
  },
  {
    id: "dr-bagel-pb",
    name: "Bagel & Peanut Butter",
    ingredients: ["Bagel", "Peanut Butter"],
    calories: "400", protein: "14", time: "3 min",
    notes: "Add banana slices or honey on top.",
  },
  {
    id: "dr-banana-pb-toast",
    name: "PB Banana Toast",
    ingredients: ["Bread", "Peanut Butter", "Banana"],
    calories: "380", protein: "12", time: "3 min",
    notes: "Drizzle honey on top. Great pre/post workout.",
  },
  {
    id: "dr-protein-shake",
    name: "Protein Shake",
    ingredients: ["Protein Powder", "Milk", "Peanut Butter"],
    calories: "380", protein: "40", time: "2 min",
    notes: "Add banana, oats, or creatine. Blend with ice.",
  },
  {
    id: "dr-smoothie",
    name: "Fruit Smoothie",
    ingredients: ["Banana", "Frozen Berries", "Milk", "Honey"],
    calories: "250", protein: "6", time: "3 min",
    notes: "Add spinach for a green boost without changing the taste.",
  },
  {
    id: "dr-overnight-oats",
    name: "Overnight Oats",
    ingredients: ["Oats", "Milk", "Chia Seeds", "Honey"],
    calories: "350", protein: "12", time: "5 min",
    notes: "Prep the night before, grab and go in the morning.",
  },
  {
    id: "dr-yogurt-parfait",
    name: "Yogurt Parfait",
    ingredients: ["Greek Yogurt", "Granola", "Honey", "Frozen Berries"],
    calories: "320", protein: "18", time: "3 min",
    notes: "Layer it in a jar for a satisfying breakfast or snack.",
  },
  {
    id: "dr-cereal",
    name: "Cereal & Milk",
    ingredients: ["Cereal", "Milk"],
    calories: "280", protein: "8", time: "1 min",
    notes: "The ultimate lazy meal. No judgment here.",
  },
  {
    id: "dr-toast-jam",
    name: "Toast & Jam",
    ingredients: ["Bread", "Butter", "Jam"],
    calories: "220", protein: "4", time: "3 min",
    notes: "Simple and satisfying. Use good bread.",
  },
  {
    id: "dr-hummus-wrap",
    name: "Hummus Veggie Wrap",
    ingredients: ["Tortilla", "Hummus", "Cucumber", "Tomato", "Lettuce"],
    calories: "310", protein: "10", time: "5 min",
    notes: "Add feta or olives for a Mediterranean twist.",
  },
  {
    id: "dr-turkey-sandwich",
    name: "Turkey Sandwich",
    ingredients: ["Bread", "Turkey", "Lettuce", "Tomato", "Mustard"],
    calories: "350", protein: "24", time: "5 min",
    notes: "Add cheese and avocado to level it up.",
  },
  {
    id: "dr-blt",
    name: "BLT",
    ingredients: ["Bread", "Bacon", "Lettuce", "Tomato", "Mayo"],
    calories: "420", protein: "16", time: "10 min",
    notes: "Toast the bread, use thick-cut bacon.",
  },
  {
    id: "dr-tuna-sandwich",
    name: "Tuna Sandwich",
    ingredients: ["Bread", "Canned Tuna", "Mayo", "Celery", "Salt", "Pepper"],
    calories: "380", protein: "28", time: "7 min",
    notes: "Add a squeeze of lemon and some diced onion.",
  },
  {
    id: "dr-caprese",
    name: "Caprese Salad",
    ingredients: ["Mozzarella", "Tomato", "Basil", "Olive Oil", "Salt"],
    calories: "280", protein: "14", time: "5 min",
    notes: "Use fresh mozzarella and ripe tomatoes.",
  },
  {
    id: "dr-ham-cheese-sandwich",
    name: "Ham & Cheese Sandwich",
    ingredients: ["Bread", "Ham", "Cheese", "Mustard", "Lettuce"],
    calories: "390", protein: "22", time: "5 min",
    notes: "Toast it for a hot sandwich upgrade.",
  },
  {
    id: "dr-cheese-crackers",
    name: "Cheese & Crackers",
    ingredients: ["Cheese", "Crackers"],
    calories: "250", protein: "10", time: "2 min",
    notes: "Add salami or grapes for a mini charcuterie.",
  },
  {
    id: "dr-pb-celery",
    name: "PB Celery Sticks",
    ingredients: ["Celery", "Peanut Butter"],
    calories: "200", protein: "8", time: "3 min",
    notes: "Add raisins for ants on a log.",
  },
  {
    id: "dr-microwave-nachos",
    name: "Microwave Nachos",
    ingredients: ["Tortilla Chips", "Cheese", "Salsa"],
    calories: "380", protein: "10", time: "3 min",
    notes: "Layer chips and cheese, microwave 90 seconds.",
  },
  {
    id: "dr-cottage-cheese-fruit",
    name: "Cottage Cheese & Fruit",
    ingredients: ["Cottage Cheese", "Banana", "Honey"],
    calories: "250", protein: "22", time: "2 min",
    notes: "High protein snack, try with peaches or berries.",
  },
  {
    id: "dr-instant-ramen",
    name: "Instant Ramen",
    ingredients: ["Instant Ramen", "Eggs", "Green Onions"],
    calories: "430", protein: "14", time: "5 min",
    notes: "Drop an egg in for the last 2 minutes of cooking.",
  },
  {
    id: "dr-english-muffin",
    name: "English Muffin with Butter",
    ingredients: ["English Muffin", "Butter", "Jam"],
    calories: "240", protein: "5", time: "3 min",
    notes: "Toast until golden and crispy.",
  },
  {
    id: "dr-rice-cake-pb",
    name: "Rice Cake with PB",
    ingredients: ["Rice Cakes", "Peanut Butter", "Honey"],
    calories: "220", protein: "7", time: "2 min",
    notes: "Light, crunchy, and satisfying snack.",
  },
  {
    id: "dr-apple-pb",
    name: "Apple & Peanut Butter",
    ingredients: ["Apple", "Peanut Butter"],
    calories: "260", protein: "7", time: "2 min",
    notes: "Slice the apple thin for max dipping.",
  },
  {
    id: "dr-wrap-turkey",
    name: "Turkey Wrap",
    ingredients: ["Tortilla", "Turkey", "Cheese", "Lettuce", "Mustard"],
    calories: "340", protein: "26", time: "5 min",
    notes: "Quick high-protein lunch to go.",
  },
  {
    id: "dr-egg-salad",
    name: "Egg Salad Sandwich",
    ingredients: ["Bread", "Eggs", "Mayo", "Mustard", "Salt", "Pepper"],
    calories: "380", protein: "18", time: "15 min",
    notes: "Boil eggs, mash, mix with mayo and mustard.",
  },
  {
    id: "dr-pita-hummus",
    name: "Pita & Hummus",
    ingredients: ["Pita Bread", "Hummus", "Cucumber", "Tomato"],
    calories: "300", protein: "10", time: "3 min",
    notes: "Warm the pita for best results.",
  },
  {
    id: "dr-banana-oat-shake",
    name: "Banana Oat Shake",
    ingredients: ["Banana", "Oats", "Milk", "Protein Powder"],
    calories: "420", protein: "32", time: "3 min",
    notes: "Blend until smooth for a filling post-workout shake.",
  },
  {
    id: "dr-hot-dog",
    name: "Hot Dog",
    ingredients: ["Hot Dog Bun", "Hot Dog", "Mustard", "Ketchup"],
    calories: "350", protein: "12", time: "5 min",
    notes: "Grill or boil, top however you like.",
  },
  {
    id: "dr-grilled-pb-banana",
    name: "Grilled PB & Banana",
    ingredients: ["Bread", "Peanut Butter", "Banana", "Butter"],
    calories: "420", protein: "14", time: "7 min",
    notes: "Like a grilled cheese but sweet. Drizzle honey inside.",
  },
  {
    id: "dr-chicken-wrap",
    name: "Chicken Wrap",
    ingredients: ["Tortilla", "Chicken Breast", "Lettuce", "Cheese", "Ranch"],
    calories: "440", protein: "32", time: "10 min",
    notes: "Use rotisserie chicken for zero-effort protein.",
  },

  // ─── BREAKFAST (28) ──────────────────────────────────────────────
  {
    id: "dr-scrambled-eggs",
    name: "Scrambled Eggs",
    ingredients: ["Eggs", "Butter", "Salt", "Pepper"],
    calories: "280", protein: "18", time: "5 min",
    notes: "Low heat, keep stirring. Pull off before they look done.",
  },
  {
    id: "dr-omelette",
    name: "Omelette",
    ingredients: ["Eggs", "Butter", "Cheese", "Salt", "Pepper"],
    calories: "350", protein: "24", time: "8 min",
    notes: "Fill with whatever's in the fridge — veggies, ham, mushrooms.",
  },
  {
    id: "dr-pancakes",
    name: "Pancakes",
    ingredients: ["Flour", "Eggs", "Milk", "Butter", "Sugar", "Baking Powder"],
    calories: "450", protein: "12", time: "20 min",
    notes: "Wait for bubbles before flipping. Serve with maple syrup.",
  },
  {
    id: "dr-waffles",
    name: "Waffles",
    ingredients: ["Flour", "Eggs", "Milk", "Butter", "Sugar", "Baking Powder"],
    calories: "460", protein: "12", time: "20 min",
    notes: "Crispy outside, fluffy inside. Top with berries.",
  },
  {
    id: "dr-french-toast",
    name: "French Toast",
    ingredients: ["Bread", "Eggs", "Milk", "Butter", "Cinnamon", "Sugar"],
    calories: "420", protein: "14", time: "15 min",
    notes: "Use thick bread like brioche or challah.",
  },
  {
    id: "dr-breakfast-burrito",
    name: "Breakfast Burrito",
    ingredients: ["Tortilla", "Eggs", "Cheese", "Salsa", "Bacon"],
    calories: "520", protein: "28", time: "12 min",
    notes: "Scramble eggs, load the tortilla, wrap tight.",
  },
  {
    id: "dr-eggs-benedict",
    name: "Eggs Benedict",
    ingredients: ["English Muffin", "Eggs", "Ham", "Butter", "Lemon Juice"],
    calories: "550", protein: "24", time: "25 min",
    notes: "Hollandaise is just butter, egg yolk, and lemon.",
  },
  {
    id: "dr-shakshuka",
    name: "Shakshuka",
    ingredients: ["Eggs", "Canned Tomatoes", "Onions", "Garlic", "Cumin", "Olive Oil"],
    calories: "320", protein: "18", time: "25 min",
    notes: "Serve with crusty bread to soak up the sauce.",
  },
  {
    id: "dr-acai-bowl",
    name: "Acai Bowl",
    ingredients: ["Acai Packet", "Banana", "Frozen Berries", "Granola", "Honey"],
    calories: "380", protein: "8", time: "5 min",
    notes: "Blend acai thick, top with granola and fruit.",
  },
  {
    id: "dr-granola-bowl",
    name: "Granola Bowl",
    ingredients: ["Granola", "Greek Yogurt", "Honey", "Banana"],
    calories: "400", protein: "16", time: "3 min",
    notes: "Crunchy, creamy, and filling. Add any fruit.",
  },
  {
    id: "dr-hash-browns",
    name: "Hash Browns",
    ingredients: ["Potatoes", "Butter", "Salt", "Pepper"],
    calories: "300", protein: "4", time: "20 min",
    notes: "Squeeze out moisture for max crispiness.",
  },
  {
    id: "dr-breakfast-sandwich",
    name: "Breakfast Sandwich",
    ingredients: ["English Muffin", "Eggs", "Cheese", "Bacon"],
    calories: "450", protein: "26", time: "10 min",
    notes: "The classic egg-cheese-bacon stack.",
  },
  {
    id: "dr-egg-muffins",
    name: "Egg Muffins",
    ingredients: ["Eggs", "Cheese", "Bell Pepper", "Salt", "Pepper"],
    calories: "220", protein: "18", time: "25 min",
    notes: "Meal prep a batch, reheat all week.",
  },
  {
    id: "dr-fried-eggs",
    name: "Fried Eggs",
    ingredients: ["Eggs", "Butter", "Salt", "Pepper"],
    calories: "220", protein: "14", time: "4 min",
    notes: "Sunny side up or over easy — don't overcook the yolk.",
  },
  {
    id: "dr-oatmeal",
    name: "Oatmeal",
    ingredients: ["Oats", "Milk", "Honey", "Banana"],
    calories: "350", protein: "10", time: "5 min",
    notes: "Add peanut butter or cinnamon for extra flavor.",
  },
  {
    id: "dr-crepes",
    name: "Crepes",
    ingredients: ["Flour", "Eggs", "Milk", "Butter", "Sugar"],
    calories: "380", protein: "10", time: "20 min",
    notes: "Swirl batter thin, fill with Nutella and fruit.",
  },
  {
    id: "dr-breakfast-quesadilla",
    name: "Breakfast Quesadilla",
    ingredients: ["Tortilla", "Eggs", "Cheese", "Salsa"],
    calories: "420", protein: "22", time: "10 min",
    notes: "Scramble eggs first, then fill and crisp the tortilla.",
  },
  {
    id: "dr-boiled-eggs",
    name: "Hard Boiled Eggs",
    ingredients: ["Eggs", "Salt"],
    calories: "210", protein: "18", time: "12 min",
    notes: "Boil 10 min, ice bath immediately. Peel under water.",
  },
  {
    id: "dr-avocado-egg-toast",
    name: "Avocado Egg Toast",
    ingredients: ["Bread", "Avocado", "Eggs", "Salt", "Red Pepper Flakes"],
    calories: "380", protein: "16", time: "7 min",
    notes: "Mash avocado, top with a fried egg.",
  },
  {
    id: "dr-cinnamon-rolls",
    name: "Cinnamon Rolls",
    ingredients: ["Cinnamon Roll Dough", "Butter", "Cinnamon", "Sugar", "Cream Cheese"],
    calories: "420", protein: "6", time: "25 min",
    notes: "Use store-bought dough for an easy weekend treat.",
  },
  {
    id: "dr-huevos-rancheros",
    name: "Huevos Rancheros",
    ingredients: ["Tortilla", "Eggs", "Black Beans", "Salsa", "Cheese"],
    calories: "450", protein: "22", time: "15 min",
    notes: "Fry the tortilla lightly, top with eggs and salsa.",
  },
  {
    id: "dr-protein-oats",
    name: "Protein Oats",
    ingredients: ["Oats", "Protein Powder", "Milk", "Peanut Butter"],
    calories: "450", protein: "35", time: "5 min",
    notes: "Stir in protein powder after cooking for best texture.",
  },
  {
    id: "dr-fruit-salad",
    name: "Fruit Salad",
    ingredients: ["Banana", "Apple", "Frozen Berries", "Honey"],
    calories: "180", protein: "2", time: "5 min",
    notes: "Use whatever fruit is in season.",
  },
  {
    id: "dr-sausage-egg",
    name: "Sausage & Eggs",
    ingredients: ["Sausage", "Eggs", "Butter", "Salt", "Pepper"],
    calories: "480", protein: "30", time: "12 min",
    notes: "Cook sausage first, then eggs in the same pan.",
  },
  {
    id: "dr-veggie-omelette",
    name: "Veggie Omelette",
    ingredients: ["Eggs", "Bell Pepper", "Onions", "Mushrooms", "Cheese", "Butter"],
    calories: "320", protein: "22", time: "10 min",
    notes: "Dice veggies small so they cook quickly.",
  },
  {
    id: "dr-bacon-eggs",
    name: "Bacon & Eggs",
    ingredients: ["Bacon", "Eggs", "Salt", "Pepper"],
    calories: "400", protein: "28", time: "10 min",
    notes: "Start bacon in a cold pan for even crispiness.",
  },
  {
    id: "dr-banana-pancakes",
    name: "Banana Pancakes",
    ingredients: ["Banana", "Eggs", "Oats"],
    calories: "280", protein: "14", time: "10 min",
    notes: "Just 3 ingredients — mash banana, mix with eggs and oats.",
  },
  {
    id: "dr-smoked-salmon-bagel",
    name: "Smoked Salmon Bagel",
    ingredients: ["Bagel", "Cream Cheese", "Smoked Salmon", "Capers"],
    calories: "420", protein: "22", time: "5 min",
    notes: "Add red onion and a squeeze of lemon.",
  },

  // ─── PASTA (22) ──────────────────────────────────────────────────
  {
    id: "dr-vodka-pasta",
    name: "Vodka Sauce Pasta",
    ingredients: ["Pasta", "Tomato Paste", "Garlic", "Olive Oil", "Butter", "Onions", "Salt", "Pepper"],
    calories: "520", protein: "14", time: "25 min",
    notes: "Vodka optional. Finish with pasta water for silky sauce.",
  },
  {
    id: "dr-pasta-aglio",
    name: "Pasta Aglio e Olio",
    ingredients: ["Pasta", "Garlic", "Olive Oil", "Salt", "Pepper"],
    calories: "400", protein: "10", time: "15 min",
    notes: "5 ingredients, restaurant quality. Don't burn the garlic.",
  },
  {
    id: "dr-carbonara",
    name: "Carbonara",
    ingredients: ["Pasta", "Eggs", "Bacon", "Parmesan", "Black Pepper"],
    calories: "550", protein: "24", time: "20 min",
    notes: "No cream — eggs, cheese, and pasta water do the work.",
  },
  {
    id: "dr-cacio-e-pepe",
    name: "Cacio e Pepe",
    ingredients: ["Pasta", "Parmesan", "Black Pepper", "Butter"],
    calories: "480", protein: "18", time: "15 min",
    notes: "Starchy pasta water is the secret to the creamy sauce.",
  },
  {
    id: "dr-bolognese",
    name: "Bolognese",
    ingredients: ["Pasta", "Ground Beef", "Canned Tomatoes", "Onions", "Garlic", "Olive Oil", "Salt"],
    calories: "620", protein: "32", time: "45 min",
    notes: "Low and slow. The longer it simmers, the better.",
  },
  {
    id: "dr-pesto-pasta",
    name: "Pesto Pasta",
    ingredients: ["Pasta", "Pesto", "Parmesan", "Olive Oil"],
    calories: "470", protein: "14", time: "15 min",
    notes: "Toss with cherry tomatoes and mozzarella.",
  },
  {
    id: "dr-mac-cheese",
    name: "Mac & Cheese",
    ingredients: ["Pasta", "Cheese", "Milk", "Butter", "Flour"],
    calories: "550", protein: "20", time: "20 min",
    notes: "Make a roux first for creamy, not grainy, sauce.",
  },
  {
    id: "dr-alfredo",
    name: "Fettuccine Alfredo",
    ingredients: ["Pasta", "Butter", "Parmesan", "Garlic", "Heavy Cream"],
    calories: "580", protein: "18", time: "18 min",
    notes: "Rich and indulgent. Add chicken for protein.",
  },
  {
    id: "dr-arrabiata",
    name: "Pasta Arrabiata",
    ingredients: ["Pasta", "Canned Tomatoes", "Garlic", "Red Pepper Flakes", "Olive Oil"],
    calories: "420", protein: "12", time: "18 min",
    notes: "Spicy tomato sauce — add more chili flakes to taste.",
  },
  {
    id: "dr-primavera",
    name: "Pasta Primavera",
    ingredients: ["Pasta", "Zucchini", "Bell Pepper", "Tomato", "Olive Oil", "Garlic", "Parmesan"],
    calories: "430", protein: "14", time: "20 min",
    notes: "Use whatever vegetables are in season.",
  },
  {
    id: "dr-lasagna",
    name: "Lasagna",
    ingredients: ["Lasagna Noodles", "Ground Beef", "Ricotta", "Mozzarella", "Canned Tomatoes", "Garlic"],
    calories: "650", protein: "34", time: "60 min",
    notes: "Let it rest 15 min after baking for clean slices.",
  },
  {
    id: "dr-baked-ziti",
    name: "Baked Ziti",
    ingredients: ["Pasta", "Ricotta", "Mozzarella", "Marinara Sauce", "Parmesan"],
    calories: "560", protein: "26", time: "40 min",
    notes: "Like lasagna but easier. Bake until bubbly on top.",
  },
  {
    id: "dr-pad-thai",
    name: "Pad Thai",
    ingredients: ["Rice Noodles", "Eggs", "Peanuts", "Soy Sauce", "Lime", "Green Onions", "Garlic"],
    calories: "480", protein: "16", time: "25 min",
    notes: "Add shrimp or chicken for protein.",
  },
  {
    id: "dr-lo-mein",
    name: "Lo Mein",
    ingredients: ["Noodles", "Soy Sauce", "Garlic", "Sesame Oil", "Bell Pepper", "Carrots"],
    calories: "440", protein: "12", time: "20 min",
    notes: "High heat and quick tossing gives the best texture.",
  },
  {
    id: "dr-ramen",
    name: "Ramen",
    ingredients: ["Ramen Noodles", "Soy Sauce", "Eggs", "Green Onions", "Garlic", "Sesame Oil"],
    calories: "450", protein: "18", time: "20 min",
    notes: "Soft-boil the egg separately and add at the end.",
  },
  {
    id: "dr-spaghetti-meatballs",
    name: "Spaghetti & Meatballs",
    ingredients: ["Pasta", "Ground Beef", "Bread Crumbs", "Eggs", "Marinara Sauce", "Parmesan"],
    calories: "620", protein: "30", time: "35 min",
    notes: "Bake meatballs in the oven for even cooking.",
  },
  {
    id: "dr-shrimp-scampi",
    name: "Shrimp Scampi Pasta",
    ingredients: ["Pasta", "Shrimp", "Garlic", "Butter", "Lemon Juice", "White Wine"],
    calories: "480", protein: "28", time: "20 min",
    notes: "Don't overcook the shrimp — 2 min per side max.",
  },
  {
    id: "dr-chicken-alfredo",
    name: "Chicken Alfredo",
    ingredients: ["Pasta", "Chicken Breast", "Heavy Cream", "Parmesan", "Garlic", "Butter"],
    calories: "640", protein: "36", time: "25 min",
    notes: "Slice chicken thin so it cooks quickly.",
  },
  {
    id: "dr-pasta-puttanesca",
    name: "Pasta Puttanesca",
    ingredients: ["Pasta", "Canned Tomatoes", "Olives", "Capers", "Garlic", "Olive Oil"],
    calories: "430", protein: "12", time: "20 min",
    notes: "Bold, briny, and easy from pantry staples.",
  },
  {
    id: "dr-tuna-pasta",
    name: "Tuna Pasta",
    ingredients: ["Pasta", "Canned Tuna", "Olive Oil", "Garlic", "Lemon Juice", "Capers"],
    calories: "420", protein: "26", time: "18 min",
    notes: "Budget-friendly and surprisingly delicious.",
  },
  {
    id: "dr-pasta-e-fagioli",
    name: "Pasta e Fagioli",
    ingredients: ["Pasta", "Canned Beans", "Canned Tomatoes", "Garlic", "Onions", "Olive Oil"],
    calories: "400", protein: "16", time: "25 min",
    notes: "Hearty Italian soup-stew. Great with crusty bread.",
  },
  {
    id: "dr-mushroom-pasta",
    name: "Mushroom Pasta",
    ingredients: ["Pasta", "Mushrooms", "Garlic", "Butter", "Parmesan", "Thyme"],
    calories: "450", protein: "14", time: "20 min",
    notes: "Brown the mushrooms well for deep umami flavor.",
  },

  // ─── RICE & GRAIN BOWLS (22) ─────────────────────────────────────
  {
    id: "dr-rice-beans",
    name: "Rice & Black Beans",
    ingredients: ["Rice", "Black Beans", "Garlic", "Onions", "Olive Oil", "Salt"],
    calories: "420", protein: "16", time: "25 min",
    notes: "Complete protein. Add hot sauce, lime, cilantro.",
  },
  {
    id: "dr-fried-rice",
    name: "Fried Rice",
    ingredients: ["Rice", "Eggs", "Soy Sauce", "Garlic", "Green Onions", "Sesame Oil"],
    calories: "450", protein: "15", time: "15 min",
    notes: "Use day-old rice. High heat is key.",
  },
  {
    id: "dr-burrito-bowl",
    name: "Burrito Bowl",
    ingredients: ["Rice", "Black Beans", "Chicken Breast", "Salsa", "Cheese", "Lettuce"],
    calories: "550", protein: "35", time: "20 min",
    notes: "Chipotle at home. Add sour cream and guac.",
  },
  {
    id: "dr-poke-bowl",
    name: "Poke Bowl",
    ingredients: ["Rice", "Salmon", "Soy Sauce", "Avocado", "Cucumber", "Sesame Seeds"],
    calories: "480", protein: "28", time: "15 min",
    notes: "Use sushi-grade fish. Season rice with rice vinegar.",
  },
  {
    id: "dr-teriyaki-bowl",
    name: "Chicken Teriyaki Bowl",
    ingredients: ["Rice", "Chicken Breast", "Soy Sauce", "Honey", "Garlic", "Broccoli"],
    calories: "520", protein: "34", time: "20 min",
    notes: "Make teriyaki sauce with soy, honey, garlic, and ginger.",
  },
  {
    id: "dr-bibimbap",
    name: "Bibimbap",
    ingredients: ["Rice", "Eggs", "Carrots", "Spinach", "Soy Sauce", "Sesame Oil", "Garlic"],
    calories: "480", protein: "18", time: "25 min",
    notes: "Top with a fried egg and gochujang if you have it.",
  },
  {
    id: "dr-grain-bowl",
    name: "Grain Bowl",
    ingredients: ["Quinoa", "Chicken Breast", "Avocado", "Tomato", "Lemon Juice", "Olive Oil"],
    calories: "500", protein: "30", time: "25 min",
    notes: "Swap quinoa for farro or brown rice.",
  },
  {
    id: "dr-couscous-salad",
    name: "Couscous Salad",
    ingredients: ["Couscous", "Cucumber", "Tomato", "Feta", "Olive Oil", "Lemon Juice"],
    calories: "380", protein: "12", time: "10 min",
    notes: "Couscous cooks in 5 min — just add boiling water.",
  },
  {
    id: "dr-risotto",
    name: "Risotto",
    ingredients: ["Arborio Rice", "Butter", "Parmesan", "Onions", "Chicken Broth", "White Wine"],
    calories: "480", protein: "12", time: "35 min",
    notes: "Stir constantly and add broth slowly.",
  },
  {
    id: "dr-jambalaya",
    name: "Jambalaya",
    ingredients: ["Rice", "Sausage", "Canned Tomatoes", "Onions", "Bell Pepper", "Garlic", "Cajun Seasoning"],
    calories: "550", protein: "24", time: "35 min",
    notes: "One-pot meal with big Cajun flavor.",
  },
  {
    id: "dr-chicken-rice",
    name: "Chicken & Rice",
    ingredients: ["Rice", "Chicken Breast", "Garlic", "Olive Oil", "Salt", "Pepper"],
    calories: "480", protein: "35", time: "25 min",
    notes: "Simple bodybuilding staple. Season well.",
  },
  {
    id: "dr-yellow-rice-chicken",
    name: "Yellow Rice & Chicken",
    ingredients: ["Rice", "Chicken Thighs", "Turmeric", "Garlic", "Onions", "Olive Oil"],
    calories: "520", protein: "32", time: "30 min",
    notes: "Turmeric gives the rice a golden color and earthy flavor.",
  },
  {
    id: "dr-coconut-rice",
    name: "Coconut Rice & Veggies",
    ingredients: ["Rice", "Coconut Milk", "Broccoli", "Carrots", "Soy Sauce"],
    calories: "420", protein: "8", time: "20 min",
    notes: "Cook rice in coconut milk for rich, creamy flavor.",
  },
  {
    id: "dr-mediterranean-bowl",
    name: "Mediterranean Bowl",
    ingredients: ["Rice", "Hummus", "Cucumber", "Tomato", "Feta", "Olive Oil"],
    calories: "450", protein: "14", time: "15 min",
    notes: "Fresh, light, and packed with flavor.",
  },
  {
    id: "dr-taco-rice",
    name: "Taco Rice Bowl",
    ingredients: ["Rice", "Ground Beef", "Taco Seasoning", "Cheese", "Salsa", "Lettuce"],
    calories: "560", protein: "28", time: "20 min",
    notes: "All the taco flavor without the shell mess.",
  },
  {
    id: "dr-hawaiian-rice",
    name: "Hawaiian Rice Bowl",
    ingredients: ["Rice", "Ham", "Pineapple", "Soy Sauce", "Green Onions"],
    calories: "460", protein: "20", time: "15 min",
    notes: "Sweet and savory combo that works surprisingly well.",
  },
  {
    id: "dr-curry-rice",
    name: "Curry Rice",
    ingredients: ["Rice", "Curry Paste", "Coconut Milk", "Chicken Breast", "Onions"],
    calories: "530", protein: "30", time: "25 min",
    notes: "Use store-bought curry paste for quick weeknight dinner.",
  },
  {
    id: "dr-shrimp-rice",
    name: "Garlic Shrimp & Rice",
    ingredients: ["Rice", "Shrimp", "Garlic", "Butter", "Lemon Juice", "Parsley"],
    calories: "440", protein: "28", time: "20 min",
    notes: "Cook shrimp 2 min per side, no more.",
  },
  {
    id: "dr-black-bean-bowl",
    name: "Black Bean Bowl",
    ingredients: ["Rice", "Black Beans", "Corn", "Avocado", "Salsa", "Lime"],
    calories: "460", protein: "16", time: "15 min",
    notes: "Vegan-friendly and full of fiber.",
  },
  {
    id: "dr-egg-fried-rice",
    name: "Egg Fried Rice",
    ingredients: ["Rice", "Eggs", "Soy Sauce", "Sesame Oil", "Green Onions", "Peas"],
    calories: "420", protein: "14", time: "10 min",
    notes: "Push rice to the side, scramble eggs, then mix.",
  },
  {
    id: "dr-quinoa-bowl",
    name: "Quinoa Power Bowl",
    ingredients: ["Quinoa", "Sweet Potato", "Chickpeas", "Spinach", "Olive Oil", "Lemon Juice"],
    calories: "440", protein: "16", time: "30 min",
    notes: "Roast the sweet potato and chickpeas together.",
  },
  {
    id: "dr-stuffed-peppers",
    name: "Stuffed Bell Peppers",
    ingredients: ["Bell Pepper", "Rice", "Ground Beef", "Canned Tomatoes", "Cheese", "Onions"],
    calories: "480", protein: "26", time: "40 min",
    notes: "Hollow out peppers, fill, and bake at 375F.",
  },

  // ─── CHICKEN (27) ────────────────────────────────────────────────
  {
    id: "dr-stir-fry",
    name: "Chicken Stir Fry",
    ingredients: ["Chicken Breast", "Soy Sauce", "Garlic", "Bell Pepper", "Broccoli", "Sesame Oil"],
    calories: "420", protein: "34", time: "15 min",
    notes: "High heat, don't overcrowd the pan.",
  },
  {
    id: "dr-baked-chicken",
    name: "Baked Chicken Breast",
    ingredients: ["Chicken Breast", "Olive Oil", "Salt", "Pepper", "Garlic"],
    calories: "300", protein: "40", time: "25 min",
    notes: "Bake at 400F until internal temp hits 165F.",
  },
  {
    id: "dr-chicken-thighs",
    name: "Crispy Chicken Thighs",
    ingredients: ["Chicken Thighs", "Olive Oil", "Salt", "Pepper", "Garlic", "Thyme"],
    calories: "380", protein: "32", time: "30 min",
    notes: "Skin-side down first for crispy skin.",
  },
  {
    id: "dr-chicken-parm",
    name: "Chicken Parmesan",
    ingredients: ["Chicken Breast", "Bread Crumbs", "Eggs", "Marinara Sauce", "Mozzarella", "Parmesan"],
    calories: "580", protein: "42", time: "30 min",
    notes: "Pound chicken thin for even cooking.",
  },
  {
    id: "dr-tikka-masala",
    name: "Chicken Tikka Masala",
    ingredients: ["Chicken Breast", "Greek Yogurt", "Canned Tomatoes", "Onions", "Garlic", "Garam Masala", "Heavy Cream"],
    calories: "520", protein: "36", time: "35 min",
    notes: "Marinate chicken in yogurt and spices for tender meat.",
  },
  {
    id: "dr-chicken-fajitas",
    name: "Chicken Fajitas",
    ingredients: ["Chicken Breast", "Bell Pepper", "Onions", "Tortilla", "Cumin", "Olive Oil"],
    calories: "480", protein: "34", time: "20 min",
    notes: "High heat for charred veggies and juicy chicken.",
  },
  {
    id: "dr-chicken-caesar",
    name: "Chicken Caesar Salad",
    ingredients: ["Chicken Breast", "Romaine Lettuce", "Parmesan", "Croutons", "Caesar Dressing"],
    calories: "420", protein: "36", time: "15 min",
    notes: "Grill or pan-sear the chicken, slice thin.",
  },
  {
    id: "dr-buffalo-chicken",
    name: "Buffalo Chicken",
    ingredients: ["Chicken Breast", "Hot Sauce", "Butter", "Celery", "Ranch"],
    calories: "380", protein: "36", time: "20 min",
    notes: "Shred chicken and toss in buffalo sauce.",
  },
  {
    id: "dr-honey-garlic-chicken",
    name: "Honey Garlic Chicken",
    ingredients: ["Chicken Thighs", "Honey", "Garlic", "Soy Sauce", "Olive Oil"],
    calories: "440", protein: "32", time: "25 min",
    notes: "Let the sauce caramelize for sticky, glossy coating.",
  },
  {
    id: "dr-lemon-herb-chicken",
    name: "Lemon Herb Chicken",
    ingredients: ["Chicken Breast", "Lemon Juice", "Garlic", "Olive Oil", "Thyme", "Salt"],
    calories: "320", protein: "38", time: "25 min",
    notes: "Bright and fresh — great with rice or roasted veggies.",
  },
  {
    id: "dr-chicken-soup",
    name: "Chicken Soup",
    ingredients: ["Chicken Breast", "Carrots", "Celery", "Onions", "Chicken Broth", "Noodles"],
    calories: "350", protein: "28", time: "35 min",
    notes: "The ultimate comfort food when you're feeling sick.",
  },
  {
    id: "dr-chicken-tacos",
    name: "Chicken Tacos",
    ingredients: ["Chicken Breast", "Tortilla", "Salsa", "Lettuce", "Cheese", "Lime"],
    calories: "420", protein: "32", time: "15 min",
    notes: "Season with cumin, chili powder, and garlic.",
  },
  {
    id: "dr-chicken-quesadilla",
    name: "Chicken Quesadilla",
    ingredients: ["Tortilla", "Chicken Breast", "Cheese", "Bell Pepper", "Onions"],
    calories: "480", protein: "34", time: "12 min",
    notes: "Use leftover or rotisserie chicken for speed.",
  },
  {
    id: "dr-bbq-chicken",
    name: "BBQ Chicken",
    ingredients: ["Chicken Thighs", "BBQ Sauce", "Olive Oil", "Salt", "Pepper"],
    calories: "420", protein: "30", time: "30 min",
    notes: "Brush sauce on in the last 5 minutes to avoid burning.",
  },
  {
    id: "dr-chicken-nuggets",
    name: "Homemade Chicken Nuggets",
    ingredients: ["Chicken Breast", "Bread Crumbs", "Eggs", "Salt", "Pepper", "Olive Oil"],
    calories: "400", protein: "32", time: "20 min",
    notes: "Cut chicken small, coat, and pan-fry or bake.",
  },
  {
    id: "dr-chicken-curry",
    name: "Chicken Curry",
    ingredients: ["Chicken Breast", "Coconut Milk", "Curry Powder", "Onions", "Garlic", "Rice"],
    calories: "520", protein: "32", time: "30 min",
    notes: "Serve over rice to soak up the sauce.",
  },
  {
    id: "dr-sesame-chicken",
    name: "Sesame Chicken",
    ingredients: ["Chicken Breast", "Soy Sauce", "Honey", "Sesame Oil", "Garlic", "Cornstarch"],
    calories: "460", protein: "34", time: "20 min",
    notes: "Coat chicken in cornstarch for crispy exterior.",
  },
  {
    id: "dr-chicken-lettuce-wraps",
    name: "Chicken Lettuce Wraps",
    ingredients: ["Ground Chicken", "Lettuce", "Soy Sauce", "Garlic", "Ginger", "Sesame Oil"],
    calories: "320", protein: "28", time: "15 min",
    notes: "Low-carb and fresh — use butter lettuce cups.",
  },
  {
    id: "dr-greek-chicken",
    name: "Greek Chicken",
    ingredients: ["Chicken Thighs", "Lemon Juice", "Garlic", "Oregano", "Olive Oil", "Salt"],
    calories: "380", protein: "32", time: "30 min",
    notes: "Marinate at least 30 min for best flavor.",
  },
  {
    id: "dr-chicken-fried-rice",
    name: "Chicken Fried Rice",
    ingredients: ["Rice", "Chicken Breast", "Eggs", "Soy Sauce", "Green Onions", "Sesame Oil"],
    calories: "500", protein: "30", time: "15 min",
    notes: "Use leftover rice and chicken for the easiest dinner.",
  },
  {
    id: "dr-chicken-piccata",
    name: "Chicken Piccata",
    ingredients: ["Chicken Breast", "Butter", "Lemon Juice", "Capers", "Flour", "Chicken Broth"],
    calories: "420", protein: "36", time: "20 min",
    notes: "Dredge in flour for a light crust, pan-fry.",
  },
  {
    id: "dr-chicken-marsala",
    name: "Chicken Marsala",
    ingredients: ["Chicken Breast", "Mushrooms", "Marsala Wine", "Butter", "Flour", "Garlic"],
    calories: "450", protein: "34", time: "25 min",
    notes: "Rich mushroom wine sauce makes this feel fancy.",
  },
  {
    id: "dr-orange-chicken",
    name: "Orange Chicken",
    ingredients: ["Chicken Breast", "Orange Juice", "Soy Sauce", "Garlic", "Cornstarch", "Honey"],
    calories: "480", protein: "32", time: "25 min",
    notes: "Crispy chicken tossed in sweet-tangy orange glaze.",
  },
  {
    id: "dr-chicken-burrito",
    name: "Chicken Burrito",
    ingredients: ["Tortilla", "Chicken Breast", "Rice", "Black Beans", "Cheese", "Salsa"],
    calories: "580", protein: "36", time: "15 min",
    notes: "Warm the tortilla so it wraps without tearing.",
  },
  {
    id: "dr-chicken-shawarma",
    name: "Chicken Shawarma",
    ingredients: ["Chicken Thighs", "Cumin", "Paprika", "Garlic", "Olive Oil", "Lemon Juice"],
    calories: "400", protein: "34", time: "25 min",
    notes: "Serve in pita with garlic sauce and pickled onions.",
  },
  {
    id: "dr-chicken-pot-pie",
    name: "Chicken Pot Pie",
    ingredients: ["Chicken Breast", "Peas", "Carrots", "Butter", "Flour", "Pie Crust"],
    calories: "520", protein: "26", time: "45 min",
    notes: "Use store-bought pie crust to save time.",
  },
  {
    id: "dr-grilled-chicken-salad",
    name: "Grilled Chicken Salad",
    ingredients: ["Chicken Breast", "Lettuce", "Tomato", "Cucumber", "Olive Oil", "Lemon Juice"],
    calories: "350", protein: "36", time: "15 min",
    notes: "High protein, low carb — great for cutting.",
  },

  // ─── BEEF & PORK (22) ────────────────────────────────────────────
  {
    id: "dr-steak",
    name: "Pan-Seared Steak",
    ingredients: ["Steak", "Butter", "Garlic", "Salt", "Pepper", "Thyme"],
    calories: "500", protein: "42", time: "15 min",
    notes: "Let it rest 5 min after cooking. Baste with butter.",
  },
  {
    id: "dr-burger",
    name: "Classic Burger",
    ingredients: ["Ground Beef", "Burger Bun", "Cheese", "Lettuce", "Tomato", "Ketchup"],
    calories: "580", protein: "32", time: "15 min",
    notes: "Don't press the patty — you'll lose all the juice.",
  },
  {
    id: "dr-meatloaf",
    name: "Meatloaf",
    ingredients: ["Ground Beef", "Bread Crumbs", "Eggs", "Ketchup", "Onions", "Salt"],
    calories: "480", protein: "30", time: "50 min",
    notes: "Glaze with ketchup in the last 10 min of baking.",
  },
  {
    id: "dr-beef-tacos",
    name: "Beef Tacos",
    ingredients: ["Ground Beef", "Tortilla", "Cheese", "Lettuce", "Salsa", "Taco Seasoning"],
    calories: "450", protein: "26", time: "15 min",
    notes: "Brown the beef, drain, add seasoning and water.",
  },
  {
    id: "dr-chili",
    name: "Beef Chili",
    ingredients: ["Ground Beef", "Canned Beans", "Canned Tomatoes", "Onions", "Garlic", "Chili Powder"],
    calories: "480", protein: "30", time: "40 min",
    notes: "Better the next day. Top with cheese and sour cream.",
  },
  {
    id: "dr-beef-stew",
    name: "Beef Stew",
    ingredients: ["Beef Chuck", "Potatoes", "Carrots", "Onions", "Beef Broth", "Tomato Paste"],
    calories: "450", protein: "32", time: "90 min",
    notes: "Low and slow. Sear the beef first for deep flavor.",
  },
  {
    id: "dr-pork-chops",
    name: "Pork Chops",
    ingredients: ["Pork Chops", "Olive Oil", "Garlic", "Salt", "Pepper", "Thyme"],
    calories: "400", protein: "36", time: "20 min",
    notes: "Don't overcook — 145F internal is perfect.",
  },
  {
    id: "dr-pulled-pork",
    name: "Pulled Pork",
    ingredients: ["Pork Shoulder", "BBQ Sauce", "Onions", "Garlic", "Salt", "Paprika"],
    calories: "520", protein: "34", time: "240 min",
    notes: "Slow cooker all day. Shred with forks when done.",
  },
  {
    id: "dr-carnitas",
    name: "Carnitas",
    ingredients: ["Pork Shoulder", "Lime", "Garlic", "Cumin", "Olive Oil", "Salt"],
    calories: "480", protein: "34", time: "180 min",
    notes: "Braise low and slow, then broil for crispy edges.",
  },
  {
    id: "dr-sloppy-joes",
    name: "Sloppy Joes",
    ingredients: ["Ground Beef", "Burger Bun", "Ketchup", "Onions", "Brown Sugar", "Mustard"],
    calories: "460", protein: "26", time: "20 min",
    notes: "Messy, saucy, and nostalgic.",
  },
  {
    id: "dr-beef-stir-fry",
    name: "Beef Stir Fry",
    ingredients: ["Beef Sirloin", "Soy Sauce", "Broccoli", "Garlic", "Sesame Oil", "Cornstarch"],
    calories: "440", protein: "32", time: "15 min",
    notes: "Slice beef thin against the grain for tenderness.",
  },
  {
    id: "dr-philly-cheesesteak",
    name: "Philly Cheesesteak",
    ingredients: ["Beef Sirloin", "Hoagie Roll", "Cheese", "Onions", "Bell Pepper"],
    calories: "580", protein: "34", time: "15 min",
    notes: "Freeze beef 30 min for paper-thin slices.",
  },
  {
    id: "dr-meat-sauce",
    name: "Meat Sauce",
    ingredients: ["Ground Beef", "Canned Tomatoes", "Garlic", "Onions", "Olive Oil", "Italian Seasoning"],
    calories: "350", protein: "24", time: "30 min",
    notes: "Make a big batch and freeze for quick pasta nights.",
  },
  {
    id: "dr-korean-beef",
    name: "Korean Ground Beef",
    ingredients: ["Ground Beef", "Soy Sauce", "Brown Sugar", "Garlic", "Sesame Oil", "Green Onions"],
    calories: "460", protein: "28", time: "12 min",
    notes: "Serve over rice with a fried egg on top.",
  },
  {
    id: "dr-steak-frites",
    name: "Steak Frites",
    ingredients: ["Steak", "Potatoes", "Olive Oil", "Salt", "Pepper", "Garlic"],
    calories: "620", protein: "38", time: "30 min",
    notes: "Cut fries thin, bake at 425F until crispy.",
  },
  {
    id: "dr-pork-tenderloin",
    name: "Pork Tenderloin",
    ingredients: ["Pork Tenderloin", "Olive Oil", "Garlic", "Honey", "Mustard", "Salt"],
    calories: "360", protein: "36", time: "25 min",
    notes: "Sear all sides, then finish in the oven at 400F.",
  },
  {
    id: "dr-bacon-cheeseburger",
    name: "Bacon Cheeseburger",
    ingredients: ["Ground Beef", "Burger Bun", "Cheese", "Bacon", "Lettuce", "Ketchup"],
    calories: "650", protein: "38", time: "15 min",
    notes: "Season the patty well — salt and pepper is all you need.",
  },
  {
    id: "dr-taco-meat",
    name: "Taco Meat & Rice",
    ingredients: ["Ground Beef", "Rice", "Taco Seasoning", "Salsa", "Cheese"],
    calories: "520", protein: "28", time: "15 min",
    notes: "One-pan meal — cook beef, add rice and seasoning.",
  },
  {
    id: "dr-beef-and-broccoli",
    name: "Beef & Broccoli",
    ingredients: ["Beef Sirloin", "Broccoli", "Soy Sauce", "Garlic", "Cornstarch", "Brown Sugar"],
    calories: "440", protein: "30", time: "20 min",
    notes: "Velveting the beef in cornstarch keeps it tender.",
  },
  {
    id: "dr-shepherd-pie",
    name: "Shepherd's Pie",
    ingredients: ["Ground Beef", "Potatoes", "Peas", "Carrots", "Onions", "Beef Broth"],
    calories: "520", protein: "28", time: "50 min",
    notes: "Mash the potatoes with butter and spread on top.",
  },
  {
    id: "dr-pork-fried-rice",
    name: "Pork Fried Rice",
    ingredients: ["Rice", "Pork Chops", "Eggs", "Soy Sauce", "Green Onions", "Sesame Oil"],
    calories: "480", protein: "28", time: "15 min",
    notes: "Dice pork small for quick cooking.",
  },
  {
    id: "dr-smash-burger",
    name: "Smash Burger",
    ingredients: ["Ground Beef", "Burger Bun", "Cheese", "Onions", "Pickles", "Ketchup"],
    calories: "540", protein: "30", time: "10 min",
    notes: "Smash thin on a screaming hot pan for crispy edges.",
  },

  // ─── SEAFOOD (17) ────────────────────────────────────────────────
  {
    id: "dr-salmon",
    name: "Pan-Seared Salmon",
    ingredients: ["Salmon", "Olive Oil", "Lemon Juice", "Garlic", "Salt", "Pepper"],
    calories: "400", protein: "36", time: "15 min",
    notes: "Skin-side down first. Don't move it until it releases.",
  },
  {
    id: "dr-shrimp-stir-fry",
    name: "Shrimp Stir Fry",
    ingredients: ["Shrimp", "Soy Sauce", "Garlic", "Broccoli", "Bell Pepper", "Sesame Oil"],
    calories: "320", protein: "30", time: "12 min",
    notes: "Shrimp cook fast — add them last.",
  },
  {
    id: "dr-fish-tacos",
    name: "Fish Tacos",
    ingredients: ["White Fish", "Tortilla", "Cabbage", "Lime", "Mayo", "Cumin"],
    calories: "380", protein: "26", time: "15 min",
    notes: "Season and pan-fry the fish, top with slaw.",
  },
  {
    id: "dr-tuna-steak",
    name: "Seared Tuna Steak",
    ingredients: ["Tuna Steak", "Soy Sauce", "Sesame Seeds", "Olive Oil", "Salt"],
    calories: "350", protein: "40", time: "10 min",
    notes: "Sear 1-2 min per side for rare center.",
  },
  {
    id: "dr-fish-chips",
    name: "Fish & Chips",
    ingredients: ["White Fish", "Flour", "Eggs", "Potatoes", "Salt", "Oil"],
    calories: "580", protein: "28", time: "30 min",
    notes: "Beer batter optional. Fry until golden and crispy.",
  },
  {
    id: "dr-crab-cakes",
    name: "Crab Cakes",
    ingredients: ["Crab Meat", "Bread Crumbs", "Eggs", "Mayo", "Mustard", "Old Bay"],
    calories: "320", protein: "24", time: "20 min",
    notes: "Use more crab than filler for the best texture.",
  },
  {
    id: "dr-baked-salmon",
    name: "Baked Salmon",
    ingredients: ["Salmon", "Lemon Juice", "Garlic", "Butter", "Dill", "Salt"],
    calories: "380", protein: "38", time: "20 min",
    notes: "Bake at 400F for 12-15 min. Easy and foolproof.",
  },
  {
    id: "dr-garlic-butter-shrimp",
    name: "Garlic Butter Shrimp",
    ingredients: ["Shrimp", "Butter", "Garlic", "Lemon Juice", "Parsley", "Salt"],
    calories: "280", protein: "28", time: "10 min",
    notes: "Cook in butter and garlic until just pink.",
  },
  {
    id: "dr-cajun-shrimp",
    name: "Cajun Shrimp",
    ingredients: ["Shrimp", "Cajun Seasoning", "Butter", "Garlic", "Lemon Juice"],
    calories: "260", protein: "28", time: "10 min",
    notes: "Spicy and quick — serve over rice or pasta.",
  },
  {
    id: "dr-fish-fillet",
    name: "Pan-Fried Fish Fillet",
    ingredients: ["White Fish", "Flour", "Butter", "Lemon Juice", "Salt", "Pepper"],
    calories: "340", protein: "30", time: "12 min",
    notes: "Dredge in flour, pan-fry in butter until flaky.",
  },
  {
    id: "dr-teriyaki-salmon",
    name: "Teriyaki Salmon",
    ingredients: ["Salmon", "Soy Sauce", "Honey", "Garlic", "Ginger", "Sesame Seeds"],
    calories: "420", protein: "36", time: "18 min",
    notes: "Glaze while cooking for caramelized finish.",
  },
  {
    id: "dr-coconut-shrimp",
    name: "Coconut Shrimp",
    ingredients: ["Shrimp", "Shredded Coconut", "Flour", "Eggs", "Salt", "Oil"],
    calories: "380", protein: "24", time: "20 min",
    notes: "Crispy coconut coating with sweet chili dipping sauce.",
  },
  {
    id: "dr-shrimp-tacos",
    name: "Shrimp Tacos",
    ingredients: ["Shrimp", "Tortilla", "Cabbage", "Lime", "Avocado", "Cumin"],
    calories: "360", protein: "26", time: "12 min",
    notes: "Season shrimp with cumin and chili powder.",
  },
  {
    id: "dr-lemon-butter-fish",
    name: "Lemon Butter Fish",
    ingredients: ["White Fish", "Butter", "Lemon Juice", "Capers", "Garlic", "Parsley"],
    calories: "320", protein: "30", time: "12 min",
    notes: "Simple French-style preparation. Elegant and easy.",
  },
  {
    id: "dr-salmon-bowl",
    name: "Salmon Rice Bowl",
    ingredients: ["Salmon", "Rice", "Avocado", "Soy Sauce", "Cucumber", "Sesame Seeds"],
    calories: "520", protein: "32", time: "20 min",
    notes: "Deconstructed sushi bowl — quick and satisfying.",
  },
  {
    id: "dr-tuna-melt",
    name: "Tuna Melt",
    ingredients: ["Bread", "Canned Tuna", "Cheese", "Mayo", "Butter"],
    calories: "440", protein: "30", time: "10 min",
    notes: "Open-faced under the broiler until cheese bubbles.",
  },
  {
    id: "dr-honey-garlic-salmon",
    name: "Honey Garlic Salmon",
    ingredients: ["Salmon", "Honey", "Garlic", "Soy Sauce", "Butter"],
    calories: "420", protein: "34", time: "18 min",
    notes: "Sweet and savory glaze that caramelizes beautifully.",
  },

  // ─── VEGETARIAN & VEGAN (27) ─────────────────────────────────────
  {
    id: "dr-veggie-stir-fry",
    name: "Veggie Stir Fry",
    ingredients: ["Broccoli", "Bell Pepper", "Carrots", "Soy Sauce", "Garlic", "Sesame Oil", "Rice"],
    calories: "350", protein: "10", time: "15 min",
    notes: "High heat, don't overcook — veggies should be crisp.",
  },
  {
    id: "dr-black-bean-tacos",
    name: "Black Bean Tacos",
    ingredients: ["Tortilla", "Black Beans", "Avocado", "Salsa", "Lime", "Cumin"],
    calories: "380", protein: "14", time: "10 min",
    notes: "Mash some beans for a creamy base, leave some whole.",
  },
  {
    id: "dr-lentil-soup",
    name: "Lentil Soup",
    ingredients: ["Lentils", "Carrots", "Onions", "Garlic", "Cumin", "Olive Oil"],
    calories: "320", protein: "18", time: "35 min",
    notes: "Hearty, cheap, and packed with protein and fiber.",
  },
  {
    id: "dr-chickpea-curry",
    name: "Chickpea Curry",
    ingredients: ["Chickpeas", "Coconut Milk", "Curry Powder", "Onions", "Garlic", "Canned Tomatoes"],
    calories: "420", protein: "14", time: "25 min",
    notes: "One-pot meal. Serve over rice or with naan.",
  },
  {
    id: "dr-tofu-scramble",
    name: "Tofu Scramble",
    ingredients: ["Tofu", "Turmeric", "Onions", "Bell Pepper", "Garlic", "Olive Oil"],
    calories: "280", protein: "20", time: "12 min",
    notes: "Crumble firm tofu and season like scrambled eggs.",
  },
  {
    id: "dr-veggie-burger",
    name: "Veggie Burger",
    ingredients: ["Black Beans", "Bread Crumbs", "Eggs", "Onions", "Burger Bun", "Salt"],
    calories: "380", protein: "16", time: "20 min",
    notes: "Mash beans, form patties, pan-fry until crispy.",
  },
  {
    id: "dr-falafel",
    name: "Falafel",
    ingredients: ["Chickpeas", "Garlic", "Onions", "Cumin", "Parsley", "Olive Oil"],
    calories: "350", protein: "14", time: "25 min",
    notes: "Use dried chickpeas soaked overnight, not canned.",
  },
  {
    id: "dr-eggplant-parm",
    name: "Eggplant Parmesan",
    ingredients: ["Eggplant", "Marinara Sauce", "Mozzarella", "Parmesan", "Bread Crumbs", "Eggs"],
    calories: "420", protein: "18", time: "40 min",
    notes: "Salt eggplant slices first to remove moisture.",
  },
  {
    id: "dr-sweet-potato-bowl",
    name: "Sweet Potato Bowl",
    ingredients: ["Sweet Potato", "Black Beans", "Avocado", "Lime", "Cumin", "Olive Oil"],
    calories: "440", protein: "14", time: "30 min",
    notes: "Roast sweet potato cubes at 425F until caramelized.",
  },
  {
    id: "dr-vegetable-soup",
    name: "Vegetable Soup",
    ingredients: ["Carrots", "Celery", "Potatoes", "Onions", "Garlic", "Vegetable Broth"],
    calories: "200", protein: "6", time: "30 min",
    notes: "Toss in whatever veggies you have on hand.",
  },
  {
    id: "dr-grilled-cheese-tomato",
    name: "Grilled Cheese & Tomato Soup",
    ingredients: ["Bread", "Cheese", "Butter", "Canned Tomatoes", "Garlic", "Onions"],
    calories: "500", protein: "16", time: "20 min",
    notes: "The perfect comfort food combo on a rainy day.",
  },
  {
    id: "dr-mushroom-risotto",
    name: "Mushroom Risotto",
    ingredients: ["Arborio Rice", "Mushrooms", "Onions", "Butter", "Parmesan", "Vegetable Broth"],
    calories: "480", protein: "12", time: "35 min",
    notes: "Stir patiently and add broth one ladle at a time.",
  },
  {
    id: "dr-bean-chili",
    name: "Three Bean Chili",
    ingredients: ["Black Beans", "Kidney Beans", "Pinto Beans", "Canned Tomatoes", "Onions", "Chili Powder"],
    calories: "400", protein: "22", time: "30 min",
    notes: "All the heartiness of chili, no meat needed.",
  },
  {
    id: "dr-veggie-quesadilla",
    name: "Veggie Quesadilla",
    ingredients: ["Tortilla", "Cheese", "Bell Pepper", "Onions", "Mushrooms", "Butter"],
    calories: "400", protein: "16", time: "10 min",
    notes: "Saute veggies first, then fill and crisp.",
  },
  {
    id: "dr-caprese-sandwich",
    name: "Caprese Sandwich",
    ingredients: ["Bread", "Mozzarella", "Tomato", "Basil", "Olive Oil", "Salt"],
    calories: "380", protein: "16", time: "5 min",
    notes: "Use ciabatta or focaccia for the best results.",
  },
  {
    id: "dr-spinach-pasta",
    name: "Spinach & Garlic Pasta",
    ingredients: ["Pasta", "Spinach", "Garlic", "Olive Oil", "Parmesan", "Red Pepper Flakes"],
    calories: "420", protein: "14", time: "15 min",
    notes: "Wilt spinach in garlic oil, toss with pasta.",
  },
  {
    id: "dr-vegetable-curry",
    name: "Vegetable Curry",
    ingredients: ["Potatoes", "Chickpeas", "Coconut Milk", "Curry Powder", "Onions", "Garlic"],
    calories: "400", protein: "12", time: "30 min",
    notes: "Creamy and warming. Serve with rice or naan.",
  },
  {
    id: "dr-roasted-veggies",
    name: "Roasted Vegetables",
    ingredients: ["Broccoli", "Bell Pepper", "Zucchini", "Olive Oil", "Salt", "Pepper"],
    calories: "200", protein: "6", time: "25 min",
    notes: "Roast at 425F, don't overcrowd the pan.",
  },
  {
    id: "dr-margherita-pizza",
    name: "Margherita Flatbread",
    ingredients: ["Pita Bread", "Marinara Sauce", "Mozzarella", "Basil", "Olive Oil"],
    calories: "380", protein: "16", time: "12 min",
    notes: "Use pita or naan as a quick pizza base.",
  },
  {
    id: "dr-dal",
    name: "Dal (Lentil Stew)",
    ingredients: ["Red Lentils", "Onions", "Garlic", "Turmeric", "Cumin", "Coconut Milk"],
    calories: "340", protein: "16", time: "30 min",
    notes: "Indian comfort food. Serve with rice or naan.",
  },
  {
    id: "dr-baked-potato",
    name: "Loaded Baked Potato",
    ingredients: ["Potatoes", "Butter", "Cheese", "Sour Cream", "Green Onions", "Salt"],
    calories: "420", protein: "12", time: "50 min",
    notes: "Poke holes, microwave 8 min or bake at 400F.",
  },
  {
    id: "dr-fried-tofu",
    name: "Crispy Fried Tofu",
    ingredients: ["Tofu", "Cornstarch", "Soy Sauce", "Garlic", "Sesame Oil"],
    calories: "300", protein: "20", time: "15 min",
    notes: "Press tofu dry, coat in cornstarch, pan-fry until golden.",
  },
  {
    id: "dr-bean-burrito",
    name: "Bean & Cheese Burrito",
    ingredients: ["Tortilla", "Refried Beans", "Cheese", "Salsa", "Sour Cream"],
    calories: "440", protein: "18", time: "8 min",
    notes: "Microwave or pan-fry until the tortilla is crispy.",
  },
  {
    id: "dr-peanut-noodles",
    name: "Peanut Noodles",
    ingredients: ["Noodles", "Peanut Butter", "Soy Sauce", "Lime", "Garlic", "Sesame Oil"],
    calories: "450", protein: "16", time: "15 min",
    notes: "Cold or warm — both work. Top with crushed peanuts.",
  },
  {
    id: "dr-bruschetta-pasta",
    name: "Bruschetta Pasta",
    ingredients: ["Pasta", "Tomato", "Garlic", "Basil", "Olive Oil", "Balsamic Vinegar"],
    calories: "400", protein: "12", time: "18 min",
    notes: "Fresh tomatoes make all the difference here.",
  },
  {
    id: "dr-sweet-potato-tacos",
    name: "Sweet Potato Tacos",
    ingredients: ["Tortilla", "Sweet Potato", "Black Beans", "Avocado", "Lime", "Cumin"],
    calories: "400", protein: "12", time: "25 min",
    notes: "Roast sweet potato cubes with cumin and chili powder.",
  },
  {
    id: "dr-minestrone",
    name: "Minestrone Soup",
    ingredients: ["Canned Beans", "Pasta", "Canned Tomatoes", "Carrots", "Celery", "Onions", "Garlic"],
    calories: "280", protein: "12", time: "30 min",
    notes: "Hearty Italian veggie soup. Great with bread.",
  },

  // ─── SALADS (16) ─────────────────────────────────────────────────
  {
    id: "dr-salad",
    name: "Simple Salad",
    ingredients: ["Lettuce", "Tomato", "Cucumber", "Olive Oil", "Vinegar", "Salt", "Pepper"],
    calories: "150", protein: "3", time: "5 min",
    notes: "Add chicken, eggs, or cheese for protein.",
  },
  {
    id: "dr-caesar-salad",
    name: "Caesar Salad",
    ingredients: ["Romaine Lettuce", "Parmesan", "Croutons", "Caesar Dressing", "Lemon Juice"],
    calories: "280", protein: "10", time: "5 min",
    notes: "Anchovy paste in the dressing is the secret.",
  },
  {
    id: "dr-greek-salad",
    name: "Greek Salad",
    ingredients: ["Cucumber", "Tomato", "Red Onion", "Feta", "Olives", "Olive Oil"],
    calories: "260", protein: "8", time: "8 min",
    notes: "No lettuce needed. Let it sit for flavors to meld.",
  },
  {
    id: "dr-cobb-salad",
    name: "Cobb Salad",
    ingredients: ["Lettuce", "Chicken Breast", "Bacon", "Eggs", "Avocado", "Tomato", "Blue Cheese"],
    calories: "450", protein: "34", time: "15 min",
    notes: "Arrange ingredients in rows for the classic look.",
  },
  {
    id: "dr-asian-slaw",
    name: "Asian Slaw",
    ingredients: ["Cabbage", "Carrots", "Soy Sauce", "Sesame Oil", "Rice Vinegar", "Sesame Seeds"],
    calories: "180", protein: "4", time: "10 min",
    notes: "Crunchy, tangy, and great as a side or taco topping.",
  },
  {
    id: "dr-quinoa-salad",
    name: "Quinoa Salad",
    ingredients: ["Quinoa", "Cucumber", "Tomato", "Feta", "Lemon Juice", "Olive Oil"],
    calories: "340", protein: "12", time: "20 min",
    notes: "Cook quinoa, cool it, and toss with fresh veggies.",
  },
  {
    id: "dr-kale-salad",
    name: "Kale Salad",
    ingredients: ["Kale", "Lemon Juice", "Olive Oil", "Parmesan", "Pine Nuts", "Salt"],
    calories: "220", protein: "8", time: "8 min",
    notes: "Massage the kale with oil and lemon to soften it.",
  },
  {
    id: "dr-spinach-salad",
    name: "Spinach Salad",
    ingredients: ["Spinach", "Strawberries", "Pecans", "Feta", "Balsamic Vinegar", "Olive Oil"],
    calories: "280", protein: "8", time: "5 min",
    notes: "Sweet and savory combo — great for spring.",
  },
  {
    id: "dr-taco-salad",
    name: "Taco Salad",
    ingredients: ["Lettuce", "Ground Beef", "Cheese", "Tortilla Chips", "Salsa", "Sour Cream"],
    calories: "520", protein: "26", time: "15 min",
    notes: "All the taco flavor in a crunchy bowl.",
  },
  {
    id: "dr-pasta-salad",
    name: "Pasta Salad",
    ingredients: ["Pasta", "Cucumber", "Tomato", "Olives", "Feta", "Italian Dressing"],
    calories: "380", protein: "10", time: "15 min",
    notes: "Great for potlucks and meal prep. Better cold.",
  },
  {
    id: "dr-chickpea-salad",
    name: "Chickpea Salad",
    ingredients: ["Chickpeas", "Cucumber", "Tomato", "Red Onion", "Lemon Juice", "Olive Oil"],
    calories: "300", protein: "12", time: "8 min",
    notes: "High fiber and protein. Great with pita.",
  },
  {
    id: "dr-avocado-salad",
    name: "Avocado Salad",
    ingredients: ["Avocado", "Tomato", "Red Onion", "Lime", "Cilantro", "Salt"],
    calories: "240", protein: "4", time: "5 min",
    notes: "Chunky and fresh. Basically deconstructed guacamole.",
  },
  {
    id: "dr-cucumber-salad",
    name: "Cucumber Salad",
    ingredients: ["Cucumber", "Rice Vinegar", "Sesame Oil", "Soy Sauce", "Sesame Seeds", "Garlic"],
    calories: "100", protein: "3", time: "5 min",
    notes: "Refreshing side dish. Smash the cucumbers first.",
  },
  {
    id: "dr-waldorf-salad",
    name: "Waldorf Salad",
    ingredients: ["Apple", "Celery", "Walnuts", "Greek Yogurt", "Lemon Juice", "Lettuce"],
    calories: "240", protein: "6", time: "8 min",
    notes: "Crunchy, creamy, and fruity all at once.",
  },
  {
    id: "dr-southwest-salad",
    name: "Southwest Salad",
    ingredients: ["Lettuce", "Black Beans", "Corn", "Tomato", "Avocado", "Ranch"],
    calories: "350", protein: "14", time: "8 min",
    notes: "Add grilled chicken for a full meal.",
  },
  {
    id: "dr-mediterranean-salad",
    name: "Mediterranean Salad",
    ingredients: ["Lettuce", "Cucumber", "Tomato", "Hummus", "Feta", "Olive Oil"],
    calories: "280", protein: "10", time: "8 min",
    notes: "A dollop of hummus as the dressing works perfectly.",
  },

  // ─── SOUPS & STEWS (17) ──────────────────────────────────────────
  {
    id: "dr-tomato-soup",
    name: "Tomato Soup",
    ingredients: ["Canned Tomatoes", "Onions", "Garlic", "Butter", "Heavy Cream", "Salt"],
    calories: "250", protein: "6", time: "25 min",
    notes: "Blend until smooth. Pair with grilled cheese.",
  },
  {
    id: "dr-chicken-noodle",
    name: "Chicken Noodle Soup",
    ingredients: ["Chicken Breast", "Noodles", "Carrots", "Celery", "Onions", "Chicken Broth"],
    calories: "320", protein: "26", time: "30 min",
    notes: "The ultimate comfort soup. Good for the soul.",
  },
  {
    id: "dr-french-onion",
    name: "French Onion Soup",
    ingredients: ["Onions", "Beef Broth", "Butter", "Bread", "Gruyere", "Thyme"],
    calories: "380", protein: "14", time: "45 min",
    notes: "Caramelize onions slowly — at least 30 minutes.",
  },
  {
    id: "dr-broccoli-cheddar",
    name: "Broccoli Cheddar Soup",
    ingredients: ["Broccoli", "Cheese", "Milk", "Butter", "Flour", "Onions"],
    calories: "350", protein: "14", time: "25 min",
    notes: "Make a roux base, then add broccoli and cheese.",
  },
  {
    id: "dr-potato-soup",
    name: "Potato Soup",
    ingredients: ["Potatoes", "Bacon", "Cheese", "Milk", "Butter", "Onions"],
    calories: "400", protein: "14", time: "30 min",
    notes: "Mash some potatoes for thickness, leave some chunky.",
  },
  {
    id: "dr-butternut-squash-soup",
    name: "Butternut Squash Soup",
    ingredients: ["Butternut Squash", "Onions", "Garlic", "Butter", "Chicken Broth", "Heavy Cream"],
    calories: "280", protein: "6", time: "35 min",
    notes: "Roast squash first for deeper, sweeter flavor.",
  },
  {
    id: "dr-clam-chowder",
    name: "Clam Chowder",
    ingredients: ["Canned Clams", "Potatoes", "Bacon", "Onions", "Heavy Cream", "Butter"],
    calories: "420", protein: "18", time: "35 min",
    notes: "New England style — thick, creamy, and rich.",
  },
  {
    id: "dr-tortilla-soup",
    name: "Chicken Tortilla Soup",
    ingredients: ["Chicken Breast", "Canned Tomatoes", "Black Beans", "Corn", "Tortilla Chips", "Cumin"],
    calories: "380", protein: "28", time: "30 min",
    notes: "Top with avocado, cheese, and crispy tortilla strips.",
  },
  {
    id: "dr-egg-drop-soup",
    name: "Egg Drop Soup",
    ingredients: ["Eggs", "Chicken Broth", "Cornstarch", "Green Onions", "Sesame Oil"],
    calories: "120", protein: "10", time: "10 min",
    notes: "Stir broth in a circle while drizzling in beaten eggs.",
  },
  {
    id: "dr-black-bean-soup",
    name: "Black Bean Soup",
    ingredients: ["Black Beans", "Onions", "Garlic", "Cumin", "Chicken Broth", "Lime"],
    calories: "340", protein: "18", time: "25 min",
    notes: "Blend half for creamy texture, leave half chunky.",
  },
  {
    id: "dr-split-pea-soup",
    name: "Split Pea Soup",
    ingredients: ["Split Peas", "Ham", "Carrots", "Onions", "Garlic", "Chicken Broth"],
    calories: "360", protein: "24", time: "50 min",
    notes: "Classic thick and hearty soup. Stir often.",
  },
  {
    id: "dr-corn-chowder",
    name: "Corn Chowder",
    ingredients: ["Corn", "Potatoes", "Bacon", "Onions", "Milk", "Butter"],
    calories: "380", protein: "12", time: "30 min",
    notes: "Sweet corn and smoky bacon make a perfect pair.",
  },
  {
    id: "dr-hot-sour-soup",
    name: "Hot & Sour Soup",
    ingredients: ["Tofu", "Mushrooms", "Eggs", "Soy Sauce", "Rice Vinegar", "Cornstarch"],
    calories: "180", protein: "12", time: "20 min",
    notes: "Balance the vinegar and white pepper to taste.",
  },
  {
    id: "dr-miso-soup",
    name: "Miso Soup",
    ingredients: ["Miso Paste", "Tofu", "Green Onions", "Seaweed"],
    calories: "80", protein: "6", time: "5 min",
    notes: "Don't boil after adding miso — it kills the flavor.",
  },
  {
    id: "dr-white-chicken-chili",
    name: "White Chicken Chili",
    ingredients: ["Chicken Breast", "White Beans", "Green Chiles", "Onions", "Garlic", "Cumin"],
    calories: "380", protein: "32", time: "30 min",
    notes: "Lighter than red chili but just as hearty.",
  },
  {
    id: "dr-italian-wedding",
    name: "Italian Wedding Soup",
    ingredients: ["Ground Beef", "Spinach", "Pasta", "Chicken Broth", "Eggs", "Parmesan"],
    calories: "340", protein: "22", time: "30 min",
    notes: "Tiny meatballs and greens in clear broth.",
  },
  {
    id: "dr-chili-verde",
    name: "Chili Verde",
    ingredients: ["Pork Shoulder", "Green Chiles", "Onions", "Garlic", "Cumin", "Lime"],
    calories: "420", protein: "30", time: "60 min",
    notes: "Tangy green chili. Serve with tortillas and sour cream.",
  },

  // ─── SNACKS & SIDES (17) ─────────────────────────────────────────
  {
    id: "dr-garlic-bread",
    name: "Garlic Bread",
    ingredients: ["Bread", "Butter", "Garlic", "Salt"],
    calories: "250", protein: "5", time: "10 min",
    notes: "Broil for 2 minutes at the end for crispy tops.",
  },
  {
    id: "dr-bruschetta",
    name: "Bruschetta",
    ingredients: ["Bread", "Tomato", "Garlic", "Basil", "Olive Oil", "Salt"],
    calories: "220", protein: "5", time: "10 min",
    notes: "Toast the bread, top with diced tomato mixture.",
  },
  {
    id: "dr-nachos",
    name: "Nachos",
    ingredients: ["Tortilla Chips", "Cheese", "Salsa", "Sour Cream", "Jalapenos"],
    calories: "480", protein: "14", time: "10 min",
    notes: "Layer chips and cheese, bake until melted and bubbly.",
  },
  {
    id: "dr-guacamole",
    name: "Guacamole",
    ingredients: ["Avocado", "Lime", "Onions", "Tomato", "Cilantro", "Salt"],
    calories: "200", protein: "3", time: "5 min",
    notes: "Chunky is better. Don't over-mash.",
  },
  {
    id: "dr-hummus-plate",
    name: "Hummus Plate",
    ingredients: ["Hummus", "Pita Bread", "Cucumber", "Carrots", "Olive Oil"],
    calories: "320", protein: "10", time: "5 min",
    notes: "Drizzle olive oil and paprika on top.",
  },
  {
    id: "dr-trail-mix",
    name: "Trail Mix",
    ingredients: ["Peanuts", "Almonds", "Raisins", "Chocolate Chips"],
    calories: "300", protein: "10", time: "2 min",
    notes: "Mix and portion into bags for grab-and-go snacking.",
  },
  {
    id: "dr-protein-balls",
    name: "Protein Balls",
    ingredients: ["Oats", "Peanut Butter", "Honey", "Protein Powder", "Chocolate Chips"],
    calories: "180", protein: "10", time: "10 min",
    notes: "No-bake. Mix, roll, and refrigerate.",
  },
  {
    id: "dr-deviled-eggs",
    name: "Deviled Eggs",
    ingredients: ["Eggs", "Mayo", "Mustard", "Paprika", "Salt"],
    calories: "200", protein: "12", time: "20 min",
    notes: "Boil, halve, mash yolks with filling, pipe back in.",
  },
  {
    id: "dr-mozzarella-sticks",
    name: "Mozzarella Sticks",
    ingredients: ["Mozzarella", "Bread Crumbs", "Eggs", "Flour", "Marinara Sauce"],
    calories: "350", protein: "16", time: "15 min",
    notes: "Freeze for 30 min before frying so cheese doesn't leak.",
  },
  {
    id: "dr-sweet-potato-fries",
    name: "Sweet Potato Fries",
    ingredients: ["Sweet Potato", "Olive Oil", "Salt", "Paprika"],
    calories: "220", protein: "3", time: "25 min",
    notes: "Cut thin, spread out on the pan, bake at 425F.",
  },
  {
    id: "dr-stuffed-mushrooms",
    name: "Stuffed Mushrooms",
    ingredients: ["Mushrooms", "Cream Cheese", "Garlic", "Parmesan", "Bread Crumbs"],
    calories: "200", protein: "8", time: "20 min",
    notes: "Remove stems, fill caps, bake until golden.",
  },
  {
    id: "dr-fried-plantains",
    name: "Fried Plantains",
    ingredients: ["Plantains", "Oil", "Salt"],
    calories: "250", protein: "2", time: "10 min",
    notes: "Use ripe (yellow/black) plantains for sweet ones.",
  },
  {
    id: "dr-roasted-chickpeas",
    name: "Roasted Chickpeas",
    ingredients: ["Chickpeas", "Olive Oil", "Salt", "Paprika", "Cumin"],
    calories: "200", protein: "10", time: "30 min",
    notes: "Dry them well, roast at 400F until crunchy.",
  },
  {
    id: "dr-caprese-skewers",
    name: "Caprese Skewers",
    ingredients: ["Mozzarella", "Cherry Tomatoes", "Basil", "Olive Oil", "Balsamic Vinegar"],
    calories: "180", protein: "10", time: "5 min",
    notes: "Thread on toothpicks for an easy party appetizer.",
  },
  {
    id: "dr-spinach-dip",
    name: "Spinach Artichoke Dip",
    ingredients: ["Spinach", "Cream Cheese", "Parmesan", "Garlic", "Mayo"],
    calories: "280", protein: "8", time: "25 min",
    notes: "Bake until bubbly. Serve with bread or chips.",
  },
  {
    id: "dr-corn-on-cob",
    name: "Corn on the Cob",
    ingredients: ["Corn", "Butter", "Salt", "Pepper"],
    calories: "200", protein: "4", time: "10 min",
    notes: "Boil, grill, or microwave — all work great.",
  },
  {
    id: "dr-edamame",
    name: "Edamame",
    ingredients: ["Edamame", "Salt", "Sesame Oil"],
    calories: "180", protein: "16", time: "5 min",
    notes: "Boil or microwave, sprinkle with sea salt.",
  },

  // ─── DESSERTS & DRINKS (17) ──────────────────────────────────────
  {
    id: "dr-banana-ice-cream",
    name: "Banana Ice Cream",
    ingredients: ["Banana", "Peanut Butter"],
    calories: "220", protein: "6", time: "5 min",
    notes: "Freeze bananas, blend until creamy. That's it.",
  },
  {
    id: "dr-smoothie-bowl",
    name: "Smoothie Bowl",
    ingredients: ["Banana", "Frozen Berries", "Milk", "Granola", "Honey"],
    calories: "350", protein: "8", time: "5 min",
    notes: "Blend thick, pour in bowl, add toppings.",
  },
  {
    id: "dr-protein-smoothie",
    name: "Protein Smoothie",
    ingredients: ["Protein Powder", "Banana", "Milk", "Peanut Butter", "Ice"],
    calories: "420", protein: "38", time: "3 min",
    notes: "Thick and filling — great as a meal replacement.",
  },
  {
    id: "dr-chia-pudding",
    name: "Chia Pudding",
    ingredients: ["Chia Seeds", "Milk", "Honey", "Vanilla Extract"],
    calories: "220", protein: "8", time: "5 min",
    notes: "Mix and refrigerate overnight. Top with fruit.",
  },
  {
    id: "dr-mug-cake",
    name: "Mug Cake",
    ingredients: ["Flour", "Sugar", "Eggs", "Butter", "Cocoa Powder", "Milk"],
    calories: "350", protein: "6", time: "5 min",
    notes: "Mix in a mug, microwave 90 seconds. Instant dessert.",
  },
  {
    id: "dr-fruit-dip",
    name: "Fruit & Yogurt Dip",
    ingredients: ["Greek Yogurt", "Honey", "Apple", "Banana"],
    calories: "200", protein: "10", time: "3 min",
    notes: "Mix yogurt with honey, dip sliced fruit.",
  },
  {
    id: "dr-chocolate-milk",
    name: "Chocolate Protein Milk",
    ingredients: ["Milk", "Protein Powder", "Cocoa Powder", "Honey"],
    calories: "280", protein: "32", time: "2 min",
    notes: "Shake or blend. Great post-workout recovery drink.",
  },
  {
    id: "dr-berry-smoothie",
    name: "Berry Smoothie",
    ingredients: ["Frozen Berries", "Greek Yogurt", "Milk", "Honey"],
    calories: "240", protein: "14", time: "3 min",
    notes: "Frozen berries make it thick without needing ice.",
  },
  {
    id: "dr-peanut-butter-shake",
    name: "PB Chocolate Shake",
    ingredients: ["Milk", "Peanut Butter", "Banana", "Cocoa Powder", "Honey"],
    calories: "420", protein: "16", time: "3 min",
    notes: "Tastes like a Reese's in a glass.",
  },
  {
    id: "dr-oat-cookies",
    name: "No-Bake Oat Cookies",
    ingredients: ["Oats", "Peanut Butter", "Honey", "Cocoa Powder", "Butter"],
    calories: "180", protein: "5", time: "15 min",
    notes: "Boil butter-cocoa mix, stir in oats and PB, scoop and cool.",
  },
  {
    id: "dr-rice-krispie-treats",
    name: "Rice Krispie Treats",
    ingredients: ["Cereal", "Marshmallows", "Butter"],
    calories: "200", protein: "2", time: "10 min",
    notes: "Melt marshmallows and butter, mix with cereal, press flat.",
  },
  {
    id: "dr-green-smoothie",
    name: "Green Smoothie",
    ingredients: ["Spinach", "Banana", "Milk", "Peanut Butter", "Honey"],
    calories: "280", protein: "12", time: "3 min",
    notes: "You won't taste the spinach. Promise.",
  },
  {
    id: "dr-frozen-yogurt-bark",
    name: "Frozen Yogurt Bark",
    ingredients: ["Greek Yogurt", "Honey", "Frozen Berries", "Granola"],
    calories: "220", protein: "12", time: "5 min",
    notes: "Spread yogurt on a tray, add toppings, freeze, break apart.",
  },
  {
    id: "dr-apple-crisp",
    name: "Apple Crisp",
    ingredients: ["Apple", "Oats", "Butter", "Brown Sugar", "Cinnamon", "Flour"],
    calories: "320", protein: "4", time: "35 min",
    notes: "Slice apples thin, top with crumble, bake at 375F.",
  },
  {
    id: "dr-hot-chocolate",
    name: "Hot Chocolate",
    ingredients: ["Milk", "Cocoa Powder", "Sugar", "Marshmallows"],
    calories: "220", protein: "8", time: "5 min",
    notes: "Heat milk, whisk in cocoa and sugar. Top with marshmallows.",
  },
  {
    id: "dr-mango-lassi",
    name: "Mango Lassi",
    ingredients: ["Mango", "Greek Yogurt", "Milk", "Honey"],
    calories: "240", protein: "10", time: "3 min",
    notes: "Use frozen mango chunks for a thick, cold drink.",
  },
  {
    id: "dr-banana-bread",
    name: "Banana Bread",
    ingredients: ["Banana", "Flour", "Eggs", "Sugar", "Butter", "Baking Soda"],
    calories: "280", protein: "5", time: "55 min",
    notes: "Use overripe bananas — the browner the better.",
  },
  ...RECIPES_BATCH_1,
  ...RECIPES_BATCH_2,
  ...RECIPES_BATCH_3,
];

export const DEFAULT_STAPLES = [
  "Rice", "Pasta", "Black Beans", "Olive Oil", "Butter",
  "Flour", "Sugar", "Salt", "Pepper", "Garlic",
  "Onions", "Tomato Paste", "Soy Sauce", "Vinegar", "Eggs",
  "Milk", "Bread", "Coffee", "Peanut Butter", "Protein Powder",
  "Creatine",
];
