export const STORAGE_KEYS = {
  items: "ff2-items",
  meals: "ff2-meals",
  shopping: "ff2-shopping",
  favorites: "ff2-favorites",
  lowStock: "ff2-lowstock",
  staples: "ff2-staples",
  recipes: "ff2-recipes",
  recurring: "ff2-recurring",
  macroLog: "ff2-macrolog",
  macroGoals: "ff2-macrogoals",
  gymLog: "ff2-gymlog",
  bodyWeight: "ff2-bodyweight",
};

export const DEFAULT_RECIPES = [
  {
    id: "dr-pbj",
    name: "PB&J",
    ingredients: ["Bread", "Peanut Butter", "Jam"],
    calories: "350", protein: "12", time: "3 min",
    notes: "Classic. Toast the bread for next-level.",
  },
  {
    id: "dr-grilled-cheese",
    name: "Grilled Cheese",
    ingredients: ["Bread", "Butter", "Cheese"],
    calories: "400", protein: "14", time: "8 min",
    notes: "Low heat, be patient. Add tomato soup on the side.",
  },
  {
    id: "dr-scrambled-eggs",
    name: "Scrambled Eggs",
    ingredients: ["Eggs", "Butter", "Salt", "Pepper"],
    calories: "280", protein: "18", time: "5 min",
    notes: "Low heat, keep stirring. Pull off before they look done.",
  },
  {
    id: "dr-quesadilla",
    name: "Quesadilla",
    ingredients: ["Tortilla", "Cheese", "Butter"],
    calories: "380", protein: "15", time: "7 min",
    notes: "Add chicken, beans, or veggies for a full meal.",
  },
  {
    id: "dr-vodka-pasta",
    name: "Vodka Sauce Pasta",
    ingredients: ["Pasta", "Tomato Paste", "Garlic", "Olive Oil", "Butter", "Onions", "Salt", "Pepper"],
    calories: "520", protein: "14", time: "25 min",
    notes: "Vodka optional. Finish with pasta water for silky sauce.",
  },
  {
    id: "dr-rice-beans",
    name: "Rice & Black Beans",
    ingredients: ["Rice", "Black Beans", "Garlic", "Onions", "Olive Oil", "Salt"],
    calories: "420", protein: "16", time: "25 min",
    notes: "Complete protein. Add hot sauce, lime, cilantro.",
  },
  {
    id: "dr-salad",
    name: "Simple Salad",
    ingredients: ["Lettuce", "Tomato", "Cucumber", "Olive Oil", "Vinegar", "Salt", "Pepper"],
    calories: "150", protein: "3", time: "5 min",
    notes: "Add chicken, eggs, or cheese for protein.",
  },
  {
    id: "dr-egg-toast",
    name: "Egg on Toast",
    ingredients: ["Bread", "Eggs", "Butter", "Salt", "Pepper"],
    calories: "320", protein: "16", time: "5 min",
    notes: "Fried, scrambled, or poached — dealer's choice.",
  },
  {
    id: "dr-stir-fry",
    name: "Quick Stir Fry",
    ingredients: ["Rice", "Soy Sauce", "Garlic", "Onions", "Eggs", "Olive Oil"],
    calories: "450", protein: "15", time: "15 min",
    notes: "Use day-old rice. Toss in any veggies or protein you have.",
  },
  {
    id: "dr-pasta-aglio",
    name: "Pasta Aglio e Olio",
    ingredients: ["Pasta", "Garlic", "Olive Oil", "Salt", "Pepper"],
    calories: "400", protein: "10", time: "15 min",
    notes: "5 ingredients, restaurant quality. Don't burn the garlic.",
  },
  {
    id: "dr-protein-shake",
    name: "Protein Shake",
    ingredients: ["Protein Powder", "Milk", "Peanut Butter"],
    calories: "380", protein: "40", time: "2 min",
    notes: "Add banana, oats, or creatine. Blend with ice.",
  },
  {
    id: "dr-avocado-toast",
    name: "Avocado Toast",
    ingredients: ["Bread", "Avocado", "Salt", "Pepper"],
    calories: "300", protein: "7", time: "5 min",
    notes: "Add an egg on top, everything bagel seasoning, or hot sauce.",
  },
  {
    id: "dr-omelette",
    name: "Omelette",
    ingredients: ["Eggs", "Butter", "Cheese", "Salt", "Pepper"],
    calories: "350", protein: "24", time: "8 min",
    notes: "Fill with whatever's in the fridge — veggies, ham, mushrooms.",
  },
  {
    id: "dr-garlic-bread",
    name: "Garlic Bread",
    ingredients: ["Bread", "Butter", "Garlic", "Salt"],
    calories: "250", protein: "5", time: "10 min",
    notes: "Broil for 2 minutes at the end for crispy tops.",
  },
  {
    id: "dr-banana-pb-toast",
    name: "PB Banana Toast",
    ingredients: ["Bread", "Peanut Butter", "Banana"],
    calories: "380", protein: "12", time: "3 min",
    notes: "Drizzle honey on top. Great pre/post workout.",
  },
  {
    id: "dr-bagel-cc",
    name: "Bagel & Cream Cheese",
    ingredients: ["Bagel", "Cream Cheese"],
    calories: "350", protein: "10", time: "3 min",
    notes: "Toast the bagel. Everything bagels are the move.",
  },
  {
    id: "dr-bagel-pb",
    name: "Bagel & Peanut Butter",
    ingredients: ["Bagel", "Peanut Butter"],
    calories: "400", protein: "14", time: "3 min",
    notes: "Add banana slices or honey on top.",
  },
];

export const DEFAULT_STAPLES = [
  "Rice", "Pasta", "Black Beans", "Olive Oil", "Butter",
  "Flour", "Sugar", "Salt", "Pepper", "Garlic",
  "Onions", "Tomato Paste", "Soy Sauce", "Vinegar", "Eggs",
  "Milk", "Bread", "Coffee", "Peanut Butter", "Protein Powder",
  "Creatine",
];
