export const FOODS = [
  // ─── PRODUCE: Fruits ───────────────────────────────────────────────────────
  { name: "Apple", category: "Produce", expiry_days: 30, calories: 95, protein: 0.5, carbs: 25, fat: 0.3, serving: "1 medium" },
  { name: "Banana", category: "Produce", expiry_days: 7, calories: 105, protein: 1.3, carbs: 27, fat: 0.4, serving: "1 medium" },
  { name: "Orange", category: "Produce", expiry_days: 21, calories: 62, protein: 1.2, carbs: 15, fat: 0.2, serving: "1 medium" },
  { name: "Strawberries", category: "Produce", expiry_days: 5, calories: 49, protein: 1, carbs: 12, fat: 0.5, serving: "1 cup" },
  { name: "Blueberries", category: "Produce", expiry_days: 10, calories: 84, protein: 1.1, carbs: 21, fat: 0.5, serving: "1 cup" },
  { name: "Raspberries", category: "Produce", expiry_days: 3, calories: 64, protein: 1.5, carbs: 15, fat: 0.8, serving: "1 cup" },
  { name: "Blackberries", category: "Produce", expiry_days: 4, calories: 62, protein: 2, carbs: 14, fat: 0.7, serving: "1 cup" },
  { name: "Grapes", category: "Produce", expiry_days: 14, calories: 104, protein: 1.1, carbs: 27, fat: 0.2, serving: "1 cup" },
  { name: "Watermelon", category: "Produce", expiry_days: 10, calories: 86, protein: 1.7, carbs: 22, fat: 0.4, serving: "2 cups diced" },
  { name: "Cantaloupe", category: "Produce", expiry_days: 7, calories: 54, protein: 1.3, carbs: 13, fat: 0.3, serving: "1 cup diced" },
  { name: "Honeydew Melon", category: "Produce", expiry_days: 7, calories: 61, protein: 0.9, carbs: 15, fat: 0.2, serving: "1 cup diced" },
  { name: "Pineapple", category: "Produce", expiry_days: 5, calories: 82, protein: 0.9, carbs: 22, fat: 0.2, serving: "1 cup chunks" },
  { name: "Mango", category: "Produce", expiry_days: 5, calories: 99, protein: 1.4, carbs: 25, fat: 0.6, serving: "1 cup sliced" },
  { name: "Papaya", category: "Produce", expiry_days: 5, calories: 55, protein: 0.9, carbs: 14, fat: 0.2, serving: "1 cup cubed" },
  { name: "Kiwi", category: "Produce", expiry_days: 14, calories: 42, protein: 0.8, carbs: 10, fat: 0.4, serving: "1 medium" },
  { name: "Peach", category: "Produce", expiry_days: 5, calories: 59, protein: 1.4, carbs: 14, fat: 0.4, serving: "1 medium" },
  { name: "Nectarine", category: "Produce", expiry_days: 5, calories: 62, protein: 1.5, carbs: 15, fat: 0.5, serving: "1 medium" },
  { name: "Plum", category: "Produce", expiry_days: 5, calories: 30, protein: 0.5, carbs: 8, fat: 0.2, serving: "1 medium" },
  { name: "Pear", category: "Produce", expiry_days: 7, calories: 101, protein: 0.6, carbs: 27, fat: 0.2, serving: "1 medium" },
  { name: "Cherries", category: "Produce", expiry_days: 5, calories: 97, protein: 1.6, carbs: 25, fat: 0.3, serving: "1 cup" },
  { name: "Apricot", category: "Produce", expiry_days: 4, calories: 17, protein: 0.5, carbs: 4, fat: 0.1, serving: "1 medium" },
  { name: "Lemon", category: "Produce", expiry_days: 21, calories: 17, protein: 0.6, carbs: 5, fat: 0.2, serving: "1 medium" },
  { name: "Lime", category: "Produce", expiry_days: 21, calories: 20, protein: 0.5, carbs: 7, fat: 0.1, serving: "1 medium" },
  { name: "Grapefruit", category: "Produce", expiry_days: 21, calories: 52, protein: 0.9, carbs: 13, fat: 0.2, serving: "1/2 medium" },
  { name: "Tangerine", category: "Produce", expiry_days: 14, calories: 47, protein: 0.7, carbs: 12, fat: 0.3, serving: "1 medium" },
  { name: "Clementine", category: "Produce", expiry_days: 14, calories: 35, protein: 0.6, carbs: 9, fat: 0.1, serving: "1 medium" },
  { name: "Pomegranate", category: "Produce", expiry_days: 30, calories: 83, protein: 1.7, carbs: 19, fat: 1.2, serving: "1/2 cup seeds" },
  { name: "Fig", category: "Produce", expiry_days: 3, calories: 37, protein: 0.4, carbs: 10, fat: 0.2, serving: "1 medium" },
  { name: "Dragon Fruit", category: "Produce", expiry_days: 5, calories: 60, protein: 1.2, carbs: 13, fat: 0, serving: "1 cup" },
  { name: "Passion Fruit", category: "Produce", expiry_days: 7, calories: 17, protein: 0.4, carbs: 4, fat: 0.1, serving: "1 fruit" },
  { name: "Coconut", category: "Produce", expiry_days: 14, calories: 283, protein: 2.7, carbs: 12, fat: 27, serving: "1 cup shredded" },
  { name: "Avocado", category: "Produce", expiry_days: 4, calories: 160, protein: 2, carbs: 9, fat: 15, serving: "1/2 medium" },
  { name: "Star Fruit", category: "Produce", expiry_days: 7, calories: 28, protein: 0.9, carbs: 6, fat: 0.3, serving: "1 medium" },
  { name: "Guava", category: "Produce", expiry_days: 4, calories: 37, protein: 1.4, carbs: 8, fat: 0.5, serving: "1 medium" },

  // ─── PRODUCE: Vegetables ────────────────────────────────────────────────────
  { name: "Spinach", category: "Produce", expiry_days: 5, calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1, serving: "1 cup raw" },
  { name: "Romaine Lettuce", category: "Produce", expiry_days: 7, calories: 8, protein: 0.6, carbs: 1.5, fat: 0.1, serving: "1 cup shredded" },
  { name: "Iceberg Lettuce", category: "Produce", expiry_days: 10, calories: 10, protein: 0.7, carbs: 2, fat: 0.1, serving: "1 cup shredded" },
  { name: "Arugula", category: "Produce", expiry_days: 5, calories: 5, protein: 0.5, carbs: 0.7, fat: 0.1, serving: "1 cup" },
  { name: "Kale", category: "Produce", expiry_days: 7, calories: 33, protein: 2.9, carbs: 6, fat: 0.5, serving: "1 cup raw" },
  { name: "Swiss Chard", category: "Produce", expiry_days: 5, calories: 7, protein: 0.7, carbs: 1.4, fat: 0.1, serving: "1 cup raw" },
  { name: "Collard Greens", category: "Produce", expiry_days: 5, calories: 11, protein: 0.9, carbs: 2, fat: 0.2, serving: "1 cup raw" },
  { name: "Cabbage", category: "Produce", expiry_days: 21, calories: 22, protein: 1.1, carbs: 5, fat: 0.1, serving: "1 cup shredded" },
  { name: "Red Cabbage", category: "Produce", expiry_days: 21, calories: 28, protein: 1.3, carbs: 7, fat: 0.1, serving: "1 cup shredded" },
  { name: "Broccoli", category: "Produce", expiry_days: 7, calories: 31, protein: 2.6, carbs: 6, fat: 0.3, serving: "1 cup chopped" },
  { name: "Cauliflower", category: "Produce", expiry_days: 7, calories: 25, protein: 2, carbs: 5, fat: 0.3, serving: "1 cup chopped" },
  { name: "Brussels Sprouts", category: "Produce", expiry_days: 7, calories: 56, protein: 4, carbs: 11, fat: 0.8, serving: "1 cup" },
  { name: "Asparagus", category: "Produce", expiry_days: 4, calories: 20, protein: 2.2, carbs: 3.7, fat: 0.2, serving: "5 spears" },
  { name: "Green Beans", category: "Produce", expiry_days: 7, calories: 44, protein: 2.4, carbs: 10, fat: 0.4, serving: "1 cup" },
  { name: "Sugar Snap Peas", category: "Produce", expiry_days: 5, calories: 41, protein: 2.7, carbs: 7, fat: 0.2, serving: "1 cup" },
  { name: "Peas", category: "Produce", expiry_days: 5, calories: 117, protein: 8, carbs: 21, fat: 0.6, serving: "1 cup" },
  { name: "Corn", category: "Produce", expiry_days: 3, calories: 132, protein: 5, carbs: 29, fat: 1.8, serving: "1 ear" },
  { name: "Carrot", category: "Produce", expiry_days: 21, calories: 52, protein: 1.2, carbs: 12, fat: 0.3, serving: "1 medium" },
  { name: "Beet", category: "Produce", expiry_days: 21, calories: 58, protein: 2.2, carbs: 13, fat: 0.2, serving: "1 cup sliced" },
  { name: "Parsnip", category: "Produce", expiry_days: 14, calories: 100, protein: 1.6, carbs: 24, fat: 0.4, serving: "1 medium" },
  { name: "Turnip", category: "Produce", expiry_days: 14, calories: 28, protein: 0.9, carbs: 6, fat: 0.1, serving: "1 cup cubed" },
  { name: "Radish", category: "Produce", expiry_days: 10, calories: 19, protein: 0.8, carbs: 4, fat: 0.1, serving: "1 cup sliced" },
  { name: "Potato", category: "Produce", expiry_days: 30, calories: 163, protein: 4.3, carbs: 37, fat: 0.2, serving: "1 medium" },
  { name: "Sweet Potato", category: "Produce", expiry_days: 21, calories: 103, protein: 2.3, carbs: 24, fat: 0.1, serving: "1 medium" },
  { name: "Yam", category: "Produce", expiry_days: 21, calories: 177, protein: 2.3, carbs: 42, fat: 0.3, serving: "1 cup cubed" },
  { name: "Tomato", category: "Produce", expiry_days: 7, calories: 22, protein: 1.1, carbs: 4.8, fat: 0.2, serving: "1 medium" },
  { name: "Cherry Tomato", category: "Produce", expiry_days: 7, calories: 27, protein: 1.3, carbs: 6, fat: 0.3, serving: "1 cup" },
  { name: "Roma Tomato", category: "Produce", expiry_days: 7, calories: 11, protein: 0.5, carbs: 2.4, fat: 0.1, serving: "1 medium" },
  { name: "Bell Pepper", category: "Produce", expiry_days: 10, calories: 31, protein: 1, carbs: 7, fat: 0.3, serving: "1 medium" },
  { name: "Red Bell Pepper", category: "Produce", expiry_days: 10, calories: 37, protein: 1.2, carbs: 7, fat: 0.4, serving: "1 medium" },
  { name: "Yellow Bell Pepper", category: "Produce", expiry_days: 10, calories: 50, protein: 1.9, carbs: 12, fat: 0.4, serving: "1 medium" },
  { name: "Jalapeño", category: "Produce", expiry_days: 14, calories: 4, protein: 0.1, carbs: 0.9, fat: 0.1, serving: "1 pepper" },
  { name: "Serrano Pepper", category: "Produce", expiry_days: 14, calories: 2, protein: 0.1, carbs: 0.4, fat: 0, serving: "1 pepper" },
  { name: "Banana Pepper", category: "Produce", expiry_days: 10, calories: 9, protein: 0.5, carbs: 2, fat: 0.2, serving: "1 medium" },
  { name: "Poblano Pepper", category: "Produce", expiry_days: 10, calories: 30, protein: 1.3, carbs: 7, fat: 0.3, serving: "1 pepper" },
  { name: "Eggplant", category: "Produce", expiry_days: 7, calories: 35, protein: 0.8, carbs: 9, fat: 0.2, serving: "1 cup cubed" },
  { name: "Zucchini", category: "Produce", expiry_days: 7, calories: 20, protein: 1.5, carbs: 4, fat: 0.4, serving: "1 medium" },
  { name: "Yellow Squash", category: "Produce", expiry_days: 7, calories: 36, protein: 2.6, carbs: 7, fat: 0.4, serving: "1 cup sliced" },
  { name: "Butternut Squash", category: "Produce", expiry_days: 60, calories: 82, protein: 1.8, carbs: 22, fat: 0.2, serving: "1 cup cubed" },
  { name: "Acorn Squash", category: "Produce", expiry_days: 60, calories: 56, protein: 1.1, carbs: 15, fat: 0.1, serving: "1 cup cubed" },
  { name: "Spaghetti Squash", category: "Produce", expiry_days: 30, calories: 42, protein: 1, carbs: 10, fat: 0.4, serving: "1 cup cooked" },
  { name: "Cucumber", category: "Produce", expiry_days: 7, calories: 16, protein: 0.7, carbs: 4, fat: 0.1, serving: "1 cup sliced" },
  { name: "Celery", category: "Produce", expiry_days: 14, calories: 14, protein: 0.7, carbs: 3, fat: 0.2, serving: "1 cup chopped" },
  { name: "Onion", category: "Produce", expiry_days: 30, calories: 64, protein: 1.8, carbs: 15, fat: 0.2, serving: "1 medium" },
  { name: "Red Onion", category: "Produce", expiry_days: 30, calories: 64, protein: 1.8, carbs: 15, fat: 0.2, serving: "1 medium" },
  { name: "Green Onion", category: "Produce", expiry_days: 7, calories: 19, protein: 1.1, carbs: 4, fat: 0.1, serving: "1/4 cup chopped" },
  { name: "Shallot", category: "Produce", expiry_days: 30, calories: 72, protein: 2.5, carbs: 17, fat: 0.1, serving: "1/4 cup chopped" },
  { name: "Garlic", category: "Produce", expiry_days: 30, calories: 4, protein: 0.2, carbs: 1, fat: 0, serving: "1 clove" },
  { name: "Leek", category: "Produce", expiry_days: 10, calories: 54, protein: 1.3, carbs: 13, fat: 0.3, serving: "1 cup sliced" },
  { name: "Button Mushroom", category: "Produce", expiry_days: 7, calories: 15, protein: 2.1, carbs: 2.3, fat: 0.2, serving: "1 cup sliced" },
  { name: "Portobello Mushroom", category: "Produce", expiry_days: 5, calories: 35, protein: 3.9, carbs: 5, fat: 0.6, serving: "1 cap" },
  { name: "Shiitake Mushroom", category: "Produce", expiry_days: 7, calories: 40, protein: 2.2, carbs: 10, fat: 0.5, serving: "1 cup" },
  { name: "Cremini Mushroom", category: "Produce", expiry_days: 7, calories: 15, protein: 1.5, carbs: 2.3, fat: 0.2, serving: "1 cup sliced" },
  { name: "Oyster Mushroom", category: "Produce", expiry_days: 5, calories: 28, protein: 2.8, carbs: 5, fat: 0.3, serving: "1 cup" },
  { name: "Artichoke", category: "Produce", expiry_days: 7, calories: 64, protein: 3.5, carbs: 14, fat: 0.4, serving: "1 medium" },
  { name: "Fennel", category: "Produce", expiry_days: 7, calories: 27, protein: 1.1, carbs: 6, fat: 0.2, serving: "1 cup sliced" },
  { name: "Bok Choy", category: "Produce", expiry_days: 5, calories: 9, protein: 1, carbs: 1.5, fat: 0.1, serving: "1 cup shredded" },
  { name: "Napa Cabbage", category: "Produce", expiry_days: 14, calories: 12, protein: 1.1, carbs: 2.2, fat: 0.2, serving: "1 cup shredded" },
  { name: "Endive", category: "Produce", expiry_days: 7, calories: 8, protein: 0.6, carbs: 1.7, fat: 0.1, serving: "1 cup chopped" },
  { name: "Watercress", category: "Produce", expiry_days: 4, calories: 4, protein: 0.8, carbs: 0.4, fat: 0.1, serving: "1 cup" },
  { name: "Okra", category: "Produce", expiry_days: 5, calories: 33, protein: 1.9, carbs: 7, fat: 0.2, serving: "1 cup sliced" },
  { name: "Jicama", category: "Produce", expiry_days: 14, calories: 46, protein: 0.9, carbs: 11, fat: 0.1, serving: "1 cup sliced" },

  // ─── PRODUCE: Fresh Herbs ────────────────────────────────────────────────────
  { name: "Fresh Basil", category: "Produce", expiry_days: 5, calories: 1, protein: 0.1, carbs: 0.1, fat: 0, serving: "2 tbsp chopped" },
  { name: "Fresh Cilantro", category: "Produce", expiry_days: 5, calories: 1, protein: 0.1, carbs: 0.1, fat: 0, serving: "2 tbsp chopped" },
  { name: "Fresh Parsley", category: "Produce", expiry_days: 7, calories: 1, protein: 0.1, carbs: 0.2, fat: 0, serving: "2 tbsp chopped" },
  { name: "Fresh Mint", category: "Produce", expiry_days: 5, calories: 1, protein: 0.1, carbs: 0.1, fat: 0, serving: "2 tbsp chopped" },
  { name: "Fresh Rosemary", category: "Produce", expiry_days: 14, calories: 2, protein: 0.1, carbs: 0.4, fat: 0.1, serving: "1 tbsp chopped" },
  { name: "Fresh Thyme", category: "Produce", expiry_days: 14, calories: 1, protein: 0.1, carbs: 0.3, fat: 0, serving: "1 tbsp fresh" },
  { name: "Fresh Dill", category: "Produce", expiry_days: 5, calories: 1, protein: 0.1, carbs: 0.1, fat: 0, serving: "2 tbsp chopped" },
  { name: "Fresh Chives", category: "Produce", expiry_days: 7, calories: 1, protein: 0.1, carbs: 0.1, fat: 0, serving: "2 tbsp chopped" },
  { name: "Fresh Oregano", category: "Produce", expiry_days: 7, calories: 3, protein: 0.1, carbs: 0.5, fat: 0.1, serving: "1 tbsp chopped" },
  { name: "Fresh Sage", category: "Produce", expiry_days: 7, calories: 2, protein: 0.1, carbs: 0.4, fat: 0.1, serving: "1 tbsp chopped" },
  { name: "Fresh Tarragon", category: "Produce", expiry_days: 7, calories: 5, protein: 0.4, carbs: 0.8, fat: 0.1, serving: "1 tbsp chopped" },
  { name: "Lemongrass", category: "Produce", expiry_days: 14, calories: 5, protein: 0.1, carbs: 1.2, fat: 0, serving: "1 stalk" },
  { name: "Ginger Root", category: "Produce", expiry_days: 21, calories: 5, protein: 0.1, carbs: 1.1, fat: 0.1, serving: "1 tsp grated" },

  // ─── DAIRY ──────────────────────────────────────────────────────────────────
  { name: "Whole Milk", category: "Dairy", expiry_days: 14, calories: 149, protein: 8, carbs: 12, fat: 8, serving: "1 cup" },
  { name: "2% Milk", category: "Dairy", expiry_days: 14, calories: 122, protein: 8, carbs: 12, fat: 5, serving: "1 cup" },
  { name: "Skim Milk", category: "Dairy", expiry_days: 14, calories: 83, protein: 8, carbs: 12, fat: 0.2, serving: "1 cup" },
  { name: "Oat Milk", category: "Dairy", expiry_days: 10, calories: 120, protein: 3, carbs: 16, fat: 5, serving: "1 cup" },
  { name: "Almond Milk", category: "Dairy", expiry_days: 10, calories: 30, protein: 1, carbs: 1, fat: 2.5, serving: "1 cup" },
  { name: "Soy Milk", category: "Dairy", expiry_days: 10, calories: 80, protein: 7, carbs: 4, fat: 4, serving: "1 cup" },
  { name: "Coconut Milk Beverage", category: "Dairy", expiry_days: 10, calories: 45, protein: 0.5, carbs: 2, fat: 4.5, serving: "1 cup" },
  { name: "Cheddar Cheese", category: "Dairy", expiry_days: 30, calories: 113, protein: 7, carbs: 0.4, fat: 9, serving: "1 oz" },
  { name: "Mozzarella Cheese", category: "Dairy", expiry_days: 14, calories: 85, protein: 6, carbs: 1, fat: 6, serving: "1 oz" },
  { name: "Swiss Cheese", category: "Dairy", expiry_days: 21, calories: 111, protein: 8, carbs: 1.5, fat: 8, serving: "1 oz" },
  { name: "Parmesan Cheese", category: "Dairy", expiry_days: 30, calories: 110, protein: 10, carbs: 1, fat: 7, serving: "1 oz" },
  { name: "Gouda Cheese", category: "Dairy", expiry_days: 21, calories: 101, protein: 7, carbs: 0.6, fat: 8, serving: "1 oz" },
  { name: "Brie Cheese", category: "Dairy", expiry_days: 14, calories: 95, protein: 6, carbs: 0.1, fat: 8, serving: "1 oz" },
  { name: "Cream Cheese", category: "Dairy", expiry_days: 14, calories: 99, protein: 2, carbs: 1, fat: 10, serving: "2 tbsp" },
  { name: "Cottage Cheese", category: "Dairy", expiry_days: 10, calories: 110, protein: 13, carbs: 6, fat: 5, serving: "1/2 cup" },
  { name: "Ricotta Cheese", category: "Dairy", expiry_days: 7, calories: 171, protein: 14, carbs: 6, fat: 10, serving: "1/2 cup" },
  { name: "Feta Cheese", category: "Dairy", expiry_days: 14, calories: 75, protein: 4, carbs: 1.2, fat: 6, serving: "1 oz" },
  { name: "Goat Cheese", category: "Dairy", expiry_days: 14, calories: 75, protein: 5, carbs: 0, fat: 6, serving: "1 oz" },
  { name: "Pepper Jack Cheese", category: "Dairy", expiry_days: 21, calories: 106, protein: 7, carbs: 0.4, fat: 8, serving: "1 oz" },
  { name: "Provolone Cheese", category: "Dairy", expiry_days: 21, calories: 98, protein: 7, carbs: 0.6, fat: 7, serving: "1 oz" },
  { name: "American Cheese", category: "Dairy", expiry_days: 21, calories: 94, protein: 5, carbs: 2, fat: 7, serving: "1 slice" },
  { name: "Blue Cheese", category: "Dairy", expiry_days: 21, calories: 100, protein: 6, carbs: 0.7, fat: 8, serving: "1 oz" },
  { name: "Colby Jack Cheese", category: "Dairy", expiry_days: 21, calories: 109, protein: 7, carbs: 0.4, fat: 9, serving: "1 oz" },
  { name: "Greek Yogurt Plain", category: "Dairy", expiry_days: 14, calories: 100, protein: 17, carbs: 6, fat: 0.7, serving: "6 oz" },
  { name: "Greek Yogurt Vanilla", category: "Dairy", expiry_days: 14, calories: 130, protein: 12, carbs: 15, fat: 0.5, serving: "6 oz" },
  { name: "Regular Yogurt Plain", category: "Dairy", expiry_days: 14, calories: 100, protein: 6, carbs: 12, fat: 3, serving: "6 oz" },
  { name: "Skyr", category: "Dairy", expiry_days: 14, calories: 110, protein: 17, carbs: 7, fat: 0, serving: "6 oz" },
  { name: "Butter", category: "Dairy", expiry_days: 30, calories: 102, protein: 0.1, carbs: 0, fat: 12, serving: "1 tbsp" },
  { name: "Heavy Cream", category: "Dairy", expiry_days: 14, calories: 52, protein: 0.4, carbs: 0.4, fat: 5.5, serving: "2 tbsp" },
  { name: "Half And Half", category: "Dairy", expiry_days: 14, calories: 39, protein: 0.9, carbs: 1.3, fat: 3.5, serving: "2 tbsp" },
  { name: "Sour Cream", category: "Dairy", expiry_days: 14, calories: 60, protein: 0.9, carbs: 1.2, fat: 6, serving: "2 tbsp" },
  { name: "Whipped Cream", category: "Dairy", expiry_days: 7, calories: 15, protein: 0.1, carbs: 0.6, fat: 1, serving: "2 tbsp" },
  { name: "Eggs", category: "Dairy", expiry_days: 35, calories: 72, protein: 6, carbs: 0.4, fat: 5, serving: "1 large egg" },
  { name: "Egg Whites", category: "Dairy", expiry_days: 5, calories: 25, protein: 5, carbs: 0.2, fat: 0.1, serving: "3 tbsp" },
  { name: "Kefir", category: "Dairy", expiry_days: 14, calories: 110, protein: 10, carbs: 12, fat: 2, serving: "1 cup" },
  { name: "Mascarpone Cheese", category: "Dairy", expiry_days: 7, calories: 120, protein: 2, carbs: 1, fat: 12, serving: "2 tbsp" },
  { name: "String Cheese", category: "Dairy", expiry_days: 21, calories: 80, protein: 7, carbs: 1, fat: 6, serving: "1 stick" },
  { name: "Queso Fresco", category: "Dairy", expiry_days: 10, calories: 80, protein: 5, carbs: 1, fat: 6, serving: "1 oz" },
  { name: "Lactose Free Milk", category: "Dairy", expiry_days: 14, calories: 149, protein: 8, carbs: 12, fat: 8, serving: "1 cup" },

  // ─── MEAT ────────────────────────────────────────────────────────────────────
  { name: "Chicken Breast", category: "Meat", expiry_days: 3, calories: 165, protein: 31, carbs: 0, fat: 3.6, serving: "3.5 oz" },
  { name: "Chicken Thigh", category: "Meat", expiry_days: 3, calories: 209, protein: 26, carbs: 0, fat: 11, serving: "3.5 oz" },
  { name: "Chicken Drumstick", category: "Meat", expiry_days: 3, calories: 172, protein: 23, carbs: 0, fat: 9, serving: "1 drumstick" },
  { name: "Chicken Wings", category: "Meat", expiry_days: 3, calories: 203, protein: 17, carbs: 0, fat: 14, serving: "3 wings" },
  { name: "Ground Chicken", category: "Meat", expiry_days: 2, calories: 170, protein: 20, carbs: 0, fat: 10, serving: "3.5 oz" },
  { name: "Whole Chicken", category: "Meat", expiry_days: 3, calories: 239, protein: 18, carbs: 0, fat: 18, serving: "3.5 oz" },
  { name: "Ground Beef 80/20", category: "Meat", expiry_days: 2, calories: 254, protein: 17, carbs: 0, fat: 20, serving: "3.5 oz" },
  { name: "Ground Beef 93/7", category: "Meat", expiry_days: 2, calories: 172, protein: 22, carbs: 0, fat: 9, serving: "3.5 oz" },
  { name: "Ribeye Steak", category: "Meat", expiry_days: 3, calories: 291, protein: 24, carbs: 0, fat: 21, serving: "3.5 oz" },
  { name: "New York Strip Steak", category: "Meat", expiry_days: 3, calories: 271, protein: 26, carbs: 0, fat: 18, serving: "3.5 oz" },
  { name: "Sirloin Steak", category: "Meat", expiry_days: 3, calories: 207, protein: 26, carbs: 0, fat: 11, serving: "3.5 oz" },
  { name: "Flank Steak", category: "Meat", expiry_days: 3, calories: 192, protein: 28, carbs: 0, fat: 8, serving: "3.5 oz" },
  { name: "Chuck Roast", category: "Meat", expiry_days: 3, calories: 218, protein: 23, carbs: 0, fat: 13, serving: "3.5 oz" },
  { name: "Beef Short Ribs", category: "Meat", expiry_days: 3, calories: 310, protein: 18, carbs: 0, fat: 26, serving: "3.5 oz" },
  { name: "Beef Stew Meat", category: "Meat", expiry_days: 3, calories: 208, protein: 24, carbs: 0, fat: 12, serving: "3.5 oz" },
  { name: "Beef Brisket", category: "Meat", expiry_days: 3, calories: 240, protein: 20, carbs: 0, fat: 17, serving: "3.5 oz" },
  { name: "Pork Chops", category: "Meat", expiry_days: 3, calories: 187, protein: 26, carbs: 0, fat: 9, serving: "3.5 oz" },
  { name: "Pork Tenderloin", category: "Meat", expiry_days: 3, calories: 143, protein: 26, carbs: 0, fat: 4, serving: "3.5 oz" },
  { name: "Pork Ribs", category: "Meat", expiry_days: 3, calories: 321, protein: 18, carbs: 0, fat: 27, serving: "3.5 oz" },
  { name: "Ground Pork", category: "Meat", expiry_days: 2, calories: 242, protein: 16, carbs: 0, fat: 19, serving: "3.5 oz" },
  { name: "Pork Shoulder", category: "Meat", expiry_days: 3, calories: 256, protein: 17, carbs: 0, fat: 20, serving: "3.5 oz" },
  { name: "Turkey Breast", category: "Meat", expiry_days: 3, calories: 135, protein: 30, carbs: 0, fat: 1, serving: "3.5 oz" },
  { name: "Ground Turkey", category: "Meat", expiry_days: 2, calories: 170, protein: 22, carbs: 0, fat: 9, serving: "3.5 oz" },
  { name: "Whole Turkey", category: "Meat", expiry_days: 3, calories: 189, protein: 29, carbs: 0, fat: 7, serving: "3.5 oz" },
  { name: "Lamb Chops", category: "Meat", expiry_days: 3, calories: 294, protein: 24, carbs: 0, fat: 21, serving: "3.5 oz" },
  { name: "Ground Lamb", category: "Meat", expiry_days: 2, calories: 283, protein: 17, carbs: 0, fat: 23, serving: "3.5 oz" },
  { name: "Italian Sausage", category: "Meat", expiry_days: 3, calories: 290, protein: 14, carbs: 2, fat: 25, serving: "1 link" },
  { name: "Bratwurst", category: "Meat", expiry_days: 7, calories: 283, protein: 12, carbs: 3, fat: 25, serving: "1 link" },
  { name: "Breakfast Sausage", category: "Meat", expiry_days: 7, calories: 170, protein: 8, carbs: 1, fat: 15, serving: "2 links" },
  { name: "Chorizo", category: "Meat", expiry_days: 7, calories: 273, protein: 14, carbs: 1, fat: 23, serving: "2 oz" },
  { name: "Bacon", category: "Meat", expiry_days: 7, calories: 130, protein: 9, carbs: 0.4, fat: 10, serving: "2 slices" },
  { name: "Canadian Bacon", category: "Meat", expiry_days: 7, calories: 68, protein: 10, carbs: 0.8, fat: 2.5, serving: "2 slices" },
  { name: "Ham Steak", category: "Meat", expiry_days: 5, calories: 107, protein: 18, carbs: 2, fat: 3, serving: "3 oz" },
  { name: "Hot Dogs", category: "Meat", expiry_days: 14, calories: 180, protein: 7, carbs: 2, fat: 16, serving: "1 hot dog" },
  { name: "Kielbasa", category: "Meat", expiry_days: 7, calories: 281, protein: 11, carbs: 3, fat: 25, serving: "3 oz" },
  { name: "Andouille Sausage", category: "Meat", expiry_days: 7, calories: 217, protein: 14, carbs: 1, fat: 18, serving: "2 oz" },
  { name: "Veal Cutlet", category: "Meat", expiry_days: 3, calories: 172, protein: 25, carbs: 0, fat: 7, serving: "3.5 oz" },
  { name: "Beef Liver", category: "Meat", expiry_days: 2, calories: 175, protein: 27, carbs: 4, fat: 5, serving: "3.5 oz" },
  { name: "Duck Breast", category: "Meat", expiry_days: 3, calories: 201, protein: 23, carbs: 0, fat: 11, serving: "3.5 oz" },

  // ─── SEAFOOD ─────────────────────────────────────────────────────────────────
  { name: "Salmon Fillet", category: "Seafood", expiry_days: 2, calories: 208, protein: 20, carbs: 0, fat: 13, serving: "3.5 oz" },
  { name: "Tuna Steak", category: "Seafood", expiry_days: 2, calories: 184, protein: 30, carbs: 0, fat: 6, serving: "3.5 oz" },
  { name: "Cod Fillet", category: "Seafood", expiry_days: 2, calories: 82, protein: 18, carbs: 0, fat: 0.7, serving: "3.5 oz" },
  { name: "Tilapia Fillet", category: "Seafood", expiry_days: 2, calories: 96, protein: 20, carbs: 0, fat: 2, serving: "3.5 oz" },
  { name: "Halibut Fillet", category: "Seafood", expiry_days: 2, calories: 111, protein: 23, carbs: 0, fat: 2, serving: "3.5 oz" },
  { name: "Rainbow Trout", category: "Seafood", expiry_days: 2, calories: 150, protein: 21, carbs: 0, fat: 7, serving: "3.5 oz" },
  { name: "Swordfish Steak", category: "Seafood", expiry_days: 2, calories: 144, protein: 23, carbs: 0, fat: 5, serving: "3.5 oz" },
  { name: "Mahi Mahi", category: "Seafood", expiry_days: 2, calories: 109, protein: 23, carbs: 0, fat: 1, serving: "3.5 oz" },
  { name: "Catfish Fillet", category: "Seafood", expiry_days: 2, calories: 105, protein: 18, carbs: 0, fat: 3, serving: "3.5 oz" },
  { name: "Sea Bass Fillet", category: "Seafood", expiry_days: 2, calories: 124, protein: 24, carbs: 0, fat: 2.6, serving: "3.5 oz" },
  { name: "Red Snapper", category: "Seafood", expiry_days: 2, calories: 128, protein: 26, carbs: 0, fat: 1.7, serving: "3.5 oz" },
  { name: "Shrimp", category: "Seafood", expiry_days: 2, calories: 84, protein: 18, carbs: 0.9, fat: 0.9, serving: "3 oz" },
  { name: "King Crab Legs", category: "Seafood", expiry_days: 2, calories: 84, protein: 16, carbs: 0, fat: 1.3, serving: "3 oz" },
  { name: "Lobster Tail", category: "Seafood", expiry_days: 2, calories: 98, protein: 20, carbs: 1.3, fat: 0.6, serving: "3.5 oz" },
  { name: "Sea Scallops", category: "Seafood", expiry_days: 2, calories: 100, protein: 19, carbs: 5, fat: 0.9, serving: "3.5 oz" },
  { name: "Little Neck Clams", category: "Seafood", expiry_days: 2, calories: 63, protein: 11, carbs: 2.2, fat: 0.8, serving: "3 oz" },
  { name: "Mussels", category: "Seafood", expiry_days: 2, calories: 86, protein: 12, carbs: 3.7, fat: 2.2, serving: "3 oz" },
  { name: "Oysters", category: "Seafood", expiry_days: 2, calories: 57, protein: 6, carbs: 3.3, fat: 2, serving: "3 oz" },
  { name: "Smoked Salmon", category: "Seafood", expiry_days: 14, calories: 117, protein: 18, carbs: 0, fat: 4, serving: "3 oz" },
  { name: "Canned Tuna", category: "Seafood", expiry_days: 365, calories: 109, protein: 25, carbs: 0, fat: 2.5, serving: "3 oz" },
  { name: "Canned Sardines", category: "Seafood", expiry_days: 365, calories: 190, protein: 23, carbs: 0, fat: 11, serving: "3.75 oz" },
  { name: "Canned Salmon", category: "Seafood", expiry_days: 365, calories: 130, protein: 17, carbs: 0, fat: 6, serving: "3 oz" },
  { name: "Imitation Crab Meat", category: "Seafood", expiry_days: 7, calories: 81, protein: 6, carbs: 13, fat: 0.4, serving: "3 oz" },
  { name: "Dungeness Crab", category: "Seafood", expiry_days: 2, calories: 94, protein: 19, carbs: 0.8, fat: 1, serving: "3 oz" },
  { name: "Calamari", category: "Seafood", expiry_days: 2, calories: 92, protein: 16, carbs: 3, fat: 1.4, serving: "3 oz" },
  { name: "Anchovies", category: "Seafood", expiry_days: 7, calories: 42, protein: 5.8, carbs: 0, fat: 1.9, serving: "1 oz" },
  { name: "Tilapia Frozen Fillets", category: "Seafood", expiry_days: 4, calories: 96, protein: 20, carbs: 0, fat: 2, serving: "3.5 oz" },
  { name: "Pollock Fillet", category: "Seafood", expiry_days: 2, calories: 92, protein: 19, carbs: 0, fat: 1, serving: "3.5 oz" },
  { name: "Arctic Char", category: "Seafood", expiry_days: 2, calories: 182, protein: 20, carbs: 0, fat: 11, serving: "3.5 oz" },
  { name: "Fish Sticks", category: "Seafood", expiry_days: 2, calories: 190, protein: 9, carbs: 16, fat: 8, serving: "4 pieces" },

  // ─── BAKERY ──────────────────────────────────────────────────────────────────
  { name: "White Bread", category: "Bakery", expiry_days: 7, calories: 79, protein: 2.7, carbs: 15, fat: 1, serving: "1 slice" },
  { name: "Whole Wheat Bread", category: "Bakery", expiry_days: 7, calories: 69, protein: 3.6, carbs: 12, fat: 1, serving: "1 slice" },
  { name: "Sourdough Bread", category: "Bakery", expiry_days: 7, calories: 84, protein: 3.6, carbs: 17, fat: 0.5, serving: "1 slice" },
  { name: "Rye Bread", category: "Bakery", expiry_days: 7, calories: 83, protein: 2.7, carbs: 15, fat: 1.1, serving: "1 slice" },
  { name: "Pumpernickel Bread", category: "Bakery", expiry_days: 7, calories: 80, protein: 2.8, carbs: 15, fat: 1, serving: "1 slice" },
  { name: "Ciabatta", category: "Bakery", expiry_days: 3, calories: 140, protein: 5, carbs: 28, fat: 1, serving: "1 piece (2 oz)" },
  { name: "Baguette", category: "Bakery", expiry_days: 2, calories: 162, protein: 6, carbs: 31, fat: 1, serving: "2 oz" },
  { name: "Pita Bread", category: "Bakery", expiry_days: 7, calories: 165, protein: 5.5, carbs: 33, fat: 0.7, serving: "1 pita" },
  { name: "Naan", category: "Bakery", expiry_days: 5, calories: 262, protein: 8.7, carbs: 45, fat: 5, serving: "1 piece" },
  { name: "English Muffin", category: "Bakery", expiry_days: 7, calories: 134, protein: 4.9, carbs: 26, fat: 1, serving: "1 muffin" },
  { name: "Dinner Rolls", category: "Bakery", expiry_days: 5, calories: 89, protein: 2.8, carbs: 15, fat: 2, serving: "1 roll" },
  { name: "Hamburger Buns", category: "Bakery", expiry_days: 7, calories: 120, protein: 4, carbs: 22, fat: 2, serving: "1 bun" },
  { name: "Hot Dog Buns", category: "Bakery", expiry_days: 7, calories: 120, protein: 4, carbs: 22, fat: 2, serving: "1 bun" },
  { name: "Bagel Plain", category: "Bakery", expiry_days: 5, calories: 270, protein: 11, carbs: 53, fat: 1.5, serving: "1 bagel" },
  { name: "Bagel Everything", category: "Bakery", expiry_days: 5, calories: 280, protein: 11, carbs: 54, fat: 2, serving: "1 bagel" },
  { name: "Flour Tortilla", category: "Bakery", expiry_days: 14, calories: 146, protein: 4, carbs: 25, fat: 3.5, serving: "1 medium (8\")" },
  { name: "Corn Tortilla", category: "Bakery", expiry_days: 14, calories: 52, protein: 1.4, carbs: 11, fat: 0.7, serving: "1 tortilla" },
  { name: "Croissant", category: "Bakery", expiry_days: 3, calories: 231, protein: 5, carbs: 26, fat: 12, serving: "1 medium" },
  { name: "Blueberry Muffin", category: "Bakery", expiry_days: 5, calories: 385, protein: 5.5, carbs: 55, fat: 16, serving: "1 large" },
  { name: "Bran Muffin", category: "Bakery", expiry_days: 5, calories: 305, protein: 5, carbs: 54, fat: 9, serving: "1 medium" },
  { name: "Glazed Donut", category: "Bakery", expiry_days: 3, calories: 269, protein: 3, carbs: 30, fat: 15, serving: "1 donut" },
  { name: "Cinnamon Roll", category: "Bakery", expiry_days: 3, calories: 350, protein: 5, carbs: 56, fat: 12, serving: "1 roll" },
  { name: "Cornbread", category: "Bakery", expiry_days: 5, calories: 173, protein: 3.5, carbs: 28, fat: 5, serving: "1 piece" },
  { name: "Focaccia", category: "Bakery", expiry_days: 3, calories: 251, protein: 6, carbs: 32, fat: 11, serving: "2 oz piece" },
  { name: "Brioche", category: "Bakery", expiry_days: 5, calories: 270, protein: 8, carbs: 32, fat: 13, serving: "1 slice" },
  { name: "Multigrain Bread", category: "Bakery", expiry_days: 7, calories: 79, protein: 3.5, carbs: 14, fat: 1.4, serving: "1 slice" },
  { name: "Pretzel Bun", category: "Bakery", expiry_days: 5, calories: 190, protein: 6, carbs: 34, fat: 2.5, serving: "1 bun" },

  // ─── GRAINS ──────────────────────────────────────────────────────────────────
  { name: "White Rice", category: "Grains", expiry_days: 365, calories: 206, protein: 4.3, carbs: 45, fat: 0.4, serving: "1 cup cooked" },
  { name: "Brown Rice", category: "Grains", expiry_days: 365, calories: 216, protein: 5, carbs: 45, fat: 1.8, serving: "1 cup cooked" },
  { name: "Jasmine Rice", category: "Grains", expiry_days: 365, calories: 205, protein: 4.2, carbs: 45, fat: 0.4, serving: "1 cup cooked" },
  { name: "Basmati Rice", category: "Grains", expiry_days: 365, calories: 191, protein: 3.5, carbs: 43, fat: 0.4, serving: "1 cup cooked" },
  { name: "Wild Rice", category: "Grains", expiry_days: 365, calories: 166, protein: 6.5, carbs: 35, fat: 0.6, serving: "1 cup cooked" },
  { name: "Spaghetti", category: "Grains", expiry_days: 365, calories: 220, protein: 8, carbs: 43, fat: 1.3, serving: "2 oz dry" },
  { name: "Penne", category: "Grains", expiry_days: 365, calories: 211, protein: 8, carbs: 42, fat: 1.3, serving: "2 oz dry" },
  { name: "Fettuccine", category: "Grains", expiry_days: 365, calories: 211, protein: 7.5, carbs: 43, fat: 1, serving: "2 oz dry" },
  { name: "Rigatoni", category: "Grains", expiry_days: 365, calories: 211, protein: 7.5, carbs: 42, fat: 1.3, serving: "2 oz dry" },
  { name: "Macaroni", category: "Grains", expiry_days: 365, calories: 211, protein: 7.5, carbs: 43, fat: 0.9, serving: "2 oz dry" },
  { name: "Linguine", category: "Grains", expiry_days: 365, calories: 211, protein: 7.5, carbs: 43, fat: 1, serving: "2 oz dry" },
  { name: "Orzo", category: "Grains", expiry_days: 365, calories: 211, protein: 7.5, carbs: 43, fat: 1, serving: "2 oz dry" },
  { name: "Lasagna Sheets", category: "Grains", expiry_days: 365, calories: 211, protein: 8, carbs: 43, fat: 1, serving: "2 oz dry" },
  { name: "Egg Noodles", category: "Grains", expiry_days: 365, calories: 221, protein: 7.5, carbs: 40, fat: 3, serving: "2 oz dry" },
  { name: "Ramen Noodles", category: "Grains", expiry_days: 365, calories: 356, protein: 9, carbs: 53, fat: 14, serving: "1 package" },
  { name: "Rolled Oats", category: "Grains", expiry_days: 365, calories: 150, protein: 5, carbs: 27, fat: 3, serving: "1/2 cup dry" },
  { name: "Steel Cut Oats", category: "Grains", expiry_days: 365, calories: 170, protein: 7, carbs: 29, fat: 3, serving: "1/4 cup dry" },
  { name: "Quinoa", category: "Grains", expiry_days: 365, calories: 222, protein: 8, carbs: 39, fat: 3.5, serving: "1 cup cooked" },
  { name: "Couscous", category: "Grains", expiry_days: 365, calories: 176, protein: 6, carbs: 36, fat: 0.3, serving: "1 cup cooked" },
  { name: "Barley", category: "Grains", expiry_days: 365, calories: 193, protein: 3.5, carbs: 44, fat: 0.7, serving: "1 cup cooked" },
  { name: "Bulgur Wheat", category: "Grains", expiry_days: 365, calories: 151, protein: 5.6, carbs: 34, fat: 0.4, serving: "1 cup cooked" },
  { name: "Cornmeal", category: "Grains", expiry_days: 365, calories: 110, protein: 2.5, carbs: 23, fat: 1, serving: "3 tbsp dry" },
  { name: "Breadcrumbs", category: "Grains", expiry_days: 90, calories: 107, protein: 4, carbs: 19, fat: 1.5, serving: "1/4 cup" },
  { name: "All Purpose Flour", category: "Grains", expiry_days: 365, calories: 110, protein: 3, carbs: 23, fat: 0.3, serving: "1/4 cup" },
  { name: "Whole Wheat Flour", category: "Grains", expiry_days: 180, calories: 100, protein: 4, carbs: 21, fat: 0.5, serving: "1/4 cup" },
  { name: "Cheerios", category: "Grains", expiry_days: 365, calories: 100, protein: 3, carbs: 20, fat: 2, serving: "1 cup" },
  { name: "Granola", category: "Grains", expiry_days: 90, calories: 208, protein: 4.4, carbs: 34, fat: 7.6, serving: "1/2 cup" },
  { name: "Cornflakes", category: "Grains", expiry_days: 365, calories: 100, protein: 2, carbs: 24, fat: 0.1, serving: "1 cup" },
  { name: "Bran Flakes", category: "Grains", expiry_days: 365, calories: 97, protein: 3, carbs: 23, fat: 0.8, serving: "3/4 cup" },
  { name: "Farro", category: "Grains", expiry_days: 365, calories: 220, protein: 8, carbs: 44, fat: 1.5, serving: "1/4 cup dry" },
  { name: "Polenta", category: "Grains", expiry_days: 365, calories: 70, protein: 2, carbs: 15, fat: 0.5, serving: "1/4 cup dry" },

  // ─── CONDIMENTS ──────────────────────────────────────────────────────────────
  { name: "Ketchup", category: "Condiments", expiry_days: 180, calories: 20, protein: 0.3, carbs: 5, fat: 0, serving: "1 tbsp" },
  { name: "Yellow Mustard", category: "Condiments", expiry_days: 365, calories: 9, protein: 0.5, carbs: 0.9, fat: 0.5, serving: "1 tsp" },
  { name: "Dijon Mustard", category: "Condiments", expiry_days: 365, calories: 15, protein: 1, carbs: 1, fat: 1, serving: "1 tsp" },
  { name: "Whole Grain Mustard", category: "Condiments", expiry_days: 365, calories: 10, protein: 0.5, carbs: 0.7, fat: 0.7, serving: "1 tsp" },
  { name: "Mayonnaise", category: "Condiments", expiry_days: 60, calories: 94, protein: 0.1, carbs: 0.1, fat: 10, serving: "1 tbsp" },
  { name: "Tabasco Sauce", category: "Condiments", expiry_days: 1825, calories: 0, protein: 0, carbs: 0, fat: 0, serving: "1 tsp" },
  { name: "Sriracha", category: "Condiments", expiry_days: 365, calories: 5, protein: 0.1, carbs: 1, fat: 0, serving: "1 tsp" },
  { name: "Franks RedHot", category: "Condiments", expiry_days: 365, calories: 0, protein: 0, carbs: 0, fat: 0, serving: "1 tsp" },
  { name: "Soy Sauce", category: "Condiments", expiry_days: 730, calories: 11, protein: 1.9, carbs: 1, fat: 0, serving: "1 tbsp" },
  { name: "Worcestershire Sauce", category: "Condiments", expiry_days: 365, calories: 13, protein: 0, carbs: 3, fat: 0, serving: "1 tbsp" },
  { name: "BBQ Sauce", category: "Condiments", expiry_days: 120, calories: 29, protein: 0.2, carbs: 7, fat: 0, serving: "2 tbsp" },
  { name: "Ranch Dressing", category: "Condiments", expiry_days: 90, calories: 73, protein: 0.3, carbs: 1, fat: 7.7, serving: "2 tbsp" },
  { name: "Italian Dressing", category: "Condiments", expiry_days: 90, calories: 43, protein: 0, carbs: 1.5, fat: 4, serving: "2 tbsp" },
  { name: "Balsamic Vinaigrette", category: "Condiments", expiry_days: 90, calories: 45, protein: 0, carbs: 4, fat: 3, serving: "2 tbsp" },
  { name: "Salsa", category: "Condiments", expiry_days: 14, calories: 10, protein: 0.5, carbs: 2, fat: 0, serving: "2 tbsp" },
  { name: "Guacamole", category: "Condiments", expiry_days: 3, calories: 45, protein: 0.5, carbs: 2.5, fat: 4, serving: "2 tbsp" },
  { name: "Hummus", category: "Condiments", expiry_days: 7, calories: 70, protein: 2, carbs: 6, fat: 4.5, serving: "2 tbsp" },
  { name: "Pesto", category: "Condiments", expiry_days: 7, calories: 90, protein: 2, carbs: 2, fat: 8, serving: "2 tbsp" },
  { name: "Marinara Sauce", category: "Condiments", expiry_days: 7, calories: 80, protein: 2, carbs: 12, fat: 2.5, serving: "1/2 cup" },
  { name: "Alfredo Sauce", category: "Condiments", expiry_days: 7, calories: 130, protein: 3, carbs: 4, fat: 12, serving: "1/4 cup" },
  { name: "Teriyaki Sauce", category: "Condiments", expiry_days: 180, calories: 30, protein: 1, carbs: 7, fat: 0, serving: "1 tbsp" },
  { name: "Hoisin Sauce", category: "Condiments", expiry_days: 365, calories: 35, protein: 0.5, carbs: 7, fat: 0.5, serving: "1 tbsp" },
  { name: "Fish Sauce", category: "Condiments", expiry_days: 730, calories: 10, protein: 1.4, carbs: 1, fat: 0, serving: "1 tbsp" },
  { name: "Tahini", category: "Condiments", expiry_days: 180, calories: 89, protein: 2.5, carbs: 3, fat: 8, serving: "1 tbsp" },
  { name: "Sweet Pickle Relish", category: "Condiments", expiry_days: 365, calories: 14, protein: 0.1, carbs: 3.4, fat: 0.1, serving: "1 tbsp" },
  { name: "Green Olives", category: "Condiments", expiry_days: 60, calories: 41, protein: 0.4, carbs: 2.2, fat: 3.8, serving: "5 olives" },
  { name: "Capers", category: "Condiments", expiry_days: 365, calories: 2, protein: 0.2, carbs: 0.4, fat: 0.1, serving: "1 tbsp" },
  { name: "Balsamic Vinegar", category: "Condiments", expiry_days: 1825, calories: 14, protein: 0.1, carbs: 2.7, fat: 0, serving: "1 tbsp" },
  { name: "Apple Cider Vinegar", category: "Condiments", expiry_days: 1825, calories: 3, protein: 0, carbs: 0.1, fat: 0, serving: "1 tbsp" },
  { name: "Red Wine Vinegar", category: "Condiments", expiry_days: 1825, calories: 3, protein: 0, carbs: 0.1, fat: 0, serving: "1 tbsp" },
  { name: "White Vinegar", category: "Condiments", expiry_days: 1825, calories: 3, protein: 0, carbs: 0.1, fat: 0, serving: "1 tbsp" },
  { name: "Olive Oil", category: "Condiments", expiry_days: 730, calories: 119, protein: 0, carbs: 0, fat: 14, serving: "1 tbsp" },
  { name: "Vegetable Oil", category: "Condiments", expiry_days: 365, calories: 124, protein: 0, carbs: 0, fat: 14, serving: "1 tbsp" },
  { name: "Coconut Oil", category: "Condiments", expiry_days: 730, calories: 121, protein: 0, carbs: 0, fat: 14, serving: "1 tbsp" },
  { name: "Honey", category: "Condiments", expiry_days: 1825, calories: 64, protein: 0.1, carbs: 17, fat: 0, serving: "1 tbsp" },
  { name: "Maple Syrup", category: "Condiments", expiry_days: 365, calories: 52, protein: 0, carbs: 13, fat: 0, serving: "1 tbsp" },
  { name: "Strawberry Jam", category: "Condiments", expiry_days: 180, calories: 50, protein: 0.1, carbs: 13, fat: 0, serving: "1 tbsp" },
  { name: "Grape Jelly", category: "Condiments", expiry_days: 180, calories: 50, protein: 0, carbs: 13, fat: 0, serving: "1 tbsp" },
  { name: "Orange Marmalade", category: "Condiments", expiry_days: 180, calories: 49, protein: 0.1, carbs: 13, fat: 0, serving: "1 tbsp" },
  { name: "Peanut Butter", category: "Condiments", expiry_days: 90, calories: 94, protein: 4, carbs: 3, fat: 8, serving: "1 tbsp" },
  { name: "Almond Butter", category: "Condiments", expiry_days: 90, calories: 98, protein: 3.4, carbs: 3, fat: 9, serving: "1 tbsp" },
  { name: "Nutella", category: "Condiments", expiry_days: 365, calories: 200, protein: 3, carbs: 23, fat: 11, serving: "2 tbsp" },
  { name: "Caesar Dressing", category: "Condiments", expiry_days: 60, calories: 78, protein: 0.6, carbs: 0.5, fat: 8.5, serving: "2 tbsp" },
  { name: "Thousand Island Dressing", category: "Condiments", expiry_days: 60, calories: 59, protein: 0.2, carbs: 4, fat: 5, serving: "2 tbsp" },
  { name: "Oyster Sauce", category: "Condiments", expiry_days: 365, calories: 20, protein: 0.5, carbs: 5, fat: 0, serving: "1 tbsp" },
  { name: "Sambal Oelek", category: "Condiments", expiry_days: 365, calories: 10, protein: 0.5, carbs: 2, fat: 0, serving: "1 tsp" },
  { name: "Gochujang", category: "Condiments", expiry_days: 365, calories: 40, protein: 1, carbs: 9, fat: 0.3, serving: "1 tbsp" },

  // ─── BEVERAGES ────────────────────────────────────────────────────────────────
  { name: "Orange Juice", category: "Beverages", expiry_days: 14, calories: 112, protein: 1.7, carbs: 26, fat: 0.5, serving: "1 cup" },
  { name: "Apple Juice", category: "Beverages", expiry_days: 14, calories: 114, protein: 0.2, carbs: 28, fat: 0.3, serving: "1 cup" },
  { name: "Cranberry Juice", category: "Beverages", expiry_days: 14, calories: 116, protein: 0.3, carbs: 31, fat: 0.3, serving: "1 cup" },
  { name: "Grape Juice", category: "Beverages", expiry_days: 14, calories: 152, protein: 0.9, carbs: 37, fat: 0.2, serving: "1 cup" },
  { name: "Tomato Juice", category: "Beverages", expiry_days: 14, calories: 41, protein: 1.9, carbs: 10, fat: 0.1, serving: "1 cup" },
  { name: "Lemonade", category: "Beverages", expiry_days: 14, calories: 99, protein: 0.2, carbs: 26, fat: 0, serving: "1 cup" },
  { name: "Chocolate Milk", category: "Beverages", expiry_days: 14, calories: 208, protein: 8, carbs: 30, fat: 5, serving: "1 cup" },
  { name: "Cold Brew Coffee", category: "Beverages", expiry_days: 14, calories: 5, protein: 0.3, carbs: 0, fat: 0, serving: "8 oz" },
  { name: "Green Tea", category: "Beverages", expiry_days: 7, calories: 2, protein: 0, carbs: 0, fat: 0, serving: "8 oz" },
  { name: "Black Tea", category: "Beverages", expiry_days: 7, calories: 2, protein: 0, carbs: 0.5, fat: 0, serving: "8 oz" },
  { name: "Kombucha", category: "Beverages", expiry_days: 30, calories: 30, protein: 0, carbs: 8, fat: 0, serving: "8 oz" },
  { name: "Sparkling Water", category: "Beverages", expiry_days: 365, calories: 0, protein: 0, carbs: 0, fat: 0, serving: "12 oz" },
  { name: "Cola", category: "Beverages", expiry_days: 180, calories: 140, protein: 0, carbs: 39, fat: 0, serving: "12 oz can" },
  { name: "Diet Cola", category: "Beverages", expiry_days: 180, calories: 0, protein: 0, carbs: 0, fat: 0, serving: "12 oz can" },
  { name: "Lemon Lime Soda", category: "Beverages", expiry_days: 180, calories: 140, protein: 0, carbs: 38, fat: 0, serving: "12 oz can" },
  { name: "Ginger Ale", category: "Beverages", expiry_days: 180, calories: 124, protein: 0, carbs: 32, fat: 0, serving: "12 oz can" },
  { name: "Root Beer", category: "Beverages", expiry_days: 180, calories: 152, protein: 0, carbs: 39, fat: 0, serving: "12 oz can" },
  { name: "Energy Drink", category: "Beverages", expiry_days: 365, calories: 110, protein: 1, carbs: 28, fat: 0, serving: "8.4 oz can" },
  { name: "Sports Drink", category: "Beverages", expiry_days: 365, calories: 80, protein: 0, carbs: 21, fat: 0, serving: "12 oz" },
  { name: "Coconut Water", category: "Beverages", expiry_days: 21, calories: 46, protein: 1.7, carbs: 9, fat: 0.5, serving: "8 oz" },
  { name: "Red Wine", category: "Beverages", expiry_days: 5, calories: 125, protein: 0.1, carbs: 4, fat: 0, serving: "5 oz glass" },
  { name: "White Wine", category: "Beverages", expiry_days: 5, calories: 121, protein: 0.1, carbs: 4, fat: 0, serving: "5 oz glass" },
  { name: "Beer Lager", category: "Beverages", expiry_days: 90, calories: 153, protein: 1.3, carbs: 13, fat: 0, serving: "12 oz can" },
  { name: "Light Beer", category: "Beverages", expiry_days: 90, calories: 103, protein: 0.9, carbs: 6, fat: 0, serving: "12 oz can" },
  { name: "Hard Seltzer", category: "Beverages", expiry_days: 180, calories: 100, protein: 0, carbs: 2, fat: 0, serving: "12 oz can" },
  { name: "Pineapple Juice", category: "Beverages", expiry_days: 14, calories: 130, protein: 0.5, carbs: 32, fat: 0.2, serving: "1 cup" },
  { name: "Mango Juice", category: "Beverages", expiry_days: 14, calories: 128, protein: 0.8, carbs: 33, fat: 0.3, serving: "1 cup" },
  { name: "Iced Coffee", category: "Beverages", expiry_days: 7, calories: 60, protein: 2, carbs: 9, fat: 1.5, serving: "8 oz" },
  { name: "Iced Tea", category: "Beverages", expiry_days: 7, calories: 90, protein: 0, carbs: 22, fat: 0, serving: "12 oz" },
  { name: "Herbal Tea", category: "Beverages", expiry_days: 7, calories: 2, protein: 0, carbs: 0.5, fat: 0, serving: "8 oz" },
  { name: "Vegetable Juice", category: "Beverages", expiry_days: 14, calories: 50, protein: 2, carbs: 11, fat: 0, serving: "8 oz" },

  // ─── FROZEN ───────────────────────────────────────────────────────────────────
  { name: "Frozen Mixed Vegetables", category: "Frozen", expiry_days: 270, calories: 59, protein: 3, carbs: 12, fat: 0.2, serving: "1 cup" },
  { name: "Frozen Peas", category: "Frozen", expiry_days: 270, calories: 62, protein: 4, carbs: 11, fat: 0.3, serving: "1/2 cup" },
  { name: "Frozen Corn", category: "Frozen", expiry_days: 270, calories: 66, protein: 2.5, carbs: 15, fat: 0.9, serving: "1/2 cup" },
  { name: "Frozen Broccoli", category: "Frozen", expiry_days: 270, calories: 26, protein: 2.8, carbs: 4.9, fat: 0.3, serving: "1 cup" },
  { name: "Frozen Spinach", category: "Frozen", expiry_days: 270, calories: 41, protein: 5, carbs: 6.6, fat: 0.5, serving: "1 cup" },
  { name: "Frozen Stir Fry Blend", category: "Frozen", expiry_days: 270, calories: 50, protein: 2.5, carbs: 10, fat: 0, serving: "1 cup" },
  { name: "Frozen Edamame", category: "Frozen", expiry_days: 270, calories: 188, protein: 16, carbs: 14, fat: 8, serving: "1 cup" },
  { name: "Frozen Mixed Berries", category: "Frozen", expiry_days: 365, calories: 70, protein: 0.9, carbs: 17, fat: 0.4, serving: "1 cup" },
  { name: "Frozen Strawberries", category: "Frozen", expiry_days: 365, calories: 50, protein: 0.5, carbs: 13, fat: 0.2, serving: "1 cup" },
  { name: "Frozen Mango", category: "Frozen", expiry_days: 365, calories: 107, protein: 0.8, carbs: 28, fat: 0.4, serving: "1 cup chunks" },
  { name: "Frozen Blueberries", category: "Frozen", expiry_days: 365, calories: 84, protein: 1.1, carbs: 21, fat: 0.5, serving: "1 cup" },
  { name: "Frozen Pizza Cheese", category: "Frozen", expiry_days: 180, calories: 280, protein: 12, carbs: 36, fat: 9, serving: "1/3 pizza" },
  { name: "Frozen Pizza Pepperoni", category: "Frozen", expiry_days: 180, calories: 330, protein: 14, carbs: 36, fat: 14, serving: "1/3 pizza" },
  { name: "Frozen Burrito Bean Cheese", category: "Frozen", expiry_days: 180, calories: 290, protein: 9, carbs: 48, fat: 8, serving: "1 burrito" },
  { name: "Frozen Chicken Pot Pie", category: "Frozen", expiry_days: 180, calories: 330, protein: 12, carbs: 36, fat: 16, serving: "1 pie" },
  { name: "Frozen TV Dinner", category: "Frozen", expiry_days: 180, calories: 350, protein: 16, carbs: 45, fat: 12, serving: "1 tray" },
  { name: "Lean Cuisine Meal", category: "Frozen", expiry_days: 180, calories: 260, protein: 18, carbs: 32, fat: 6, serving: "1 tray" },
  { name: "Vanilla Ice Cream", category: "Frozen", expiry_days: 180, calories: 207, protein: 3.5, carbs: 24, fat: 11, serving: "1/2 cup" },
  { name: "Chocolate Ice Cream", category: "Frozen", expiry_days: 180, calories: 218, protein: 4, carbs: 26, fat: 11, serving: "1/2 cup" },
  { name: "Strawberry Ice Cream", category: "Frozen", expiry_days: 180, calories: 184, protein: 3.3, carbs: 24, fat: 9, serving: "1/2 cup" },
  { name: "Frozen Waffles", category: "Frozen", expiry_days: 180, calories: 194, protein: 5, carbs: 30, fat: 6, serving: "2 waffles" },
  { name: "Frozen French Fries", category: "Frozen", expiry_days: 270, calories: 312, protein: 4, carbs: 42, fat: 15, serving: "3 oz" },
  { name: "Chicken Nuggets", category: "Frozen", expiry_days: 180, calories: 280, protein: 14, carbs: 18, fat: 17, serving: "6 pieces" },
  { name: "Frozen Fish Sticks", category: "Frozen", expiry_days: 180, calories: 190, protein: 9, carbs: 16, fat: 8, serving: "4 pieces" },
  { name: "Frozen Dumplings", category: "Frozen", expiry_days: 180, calories: 210, protein: 9, carbs: 28, fat: 7, serving: "6 pieces" },
  { name: "Frozen Pierogies", category: "Frozen", expiry_days: 180, calories: 190, protein: 6, carbs: 34, fat: 3.5, serving: "3 pieces" },
  { name: "Frozen Tater Tots", category: "Frozen", expiry_days: 270, calories: 160, protein: 2, carbs: 23, fat: 7, serving: "3 oz" },
  { name: "Frozen Breakfast Sandwich", category: "Frozen", expiry_days: 180, calories: 290, protein: 15, carbs: 30, fat: 12, serving: "1 sandwich" },
  { name: "Frozen Veggie Burger", category: "Frozen", expiry_days: 270, calories: 120, protein: 15, carbs: 8, fat: 3, serving: "1 patty" },
  { name: "Frozen Egg Rolls", category: "Frozen", expiry_days: 180, calories: 180, protein: 5, carbs: 22, fat: 8, serving: "2 rolls" },
  { name: "Acai Frozen Packets", category: "Frozen", expiry_days: 365, calories: 70, protein: 1, carbs: 6, fat: 5, serving: "3.5 oz packet" },

  // ─── SNACKS ───────────────────────────────────────────────────────────────────
  { name: "Potato Chips", category: "Snacks", expiry_days: 60, calories: 152, protein: 2, carbs: 15, fat: 10, serving: "1 oz" },
  { name: "Tortilla Chips", category: "Snacks", expiry_days: 60, calories: 140, protein: 2, carbs: 19, fat: 7, serving: "1 oz" },
  { name: "Pita Chips", category: "Snacks", expiry_days: 60, calories: 130, protein: 3, carbs: 19, fat: 5, serving: "1 oz" },
  { name: "Veggie Chips", category: "Snacks", expiry_days: 60, calories: 130, protein: 1, carbs: 19, fat: 6, serving: "1 oz" },
  { name: "Kettle Chips", category: "Snacks", expiry_days: 60, calories: 150, protein: 2, carbs: 16, fat: 9, serving: "1 oz" },
  { name: "Saltine Crackers", category: "Snacks", expiry_days: 180, calories: 130, protein: 3, carbs: 22, fat: 3, serving: "5 crackers" },
  { name: "Wheat Thins", category: "Snacks", expiry_days: 180, calories: 130, protein: 2, carbs: 21, fat: 4, serving: "16 crackers" },
  { name: "Ritz Crackers", category: "Snacks", expiry_days: 180, calories: 160, protein: 2, carbs: 19, fat: 8, serving: "5 crackers" },
  { name: "Graham Crackers", category: "Snacks", expiry_days: 180, calories: 130, protein: 2, carbs: 24, fat: 3, serving: "2 sheets" },
  { name: "Goldfish Crackers", category: "Snacks", expiry_days: 180, calories: 140, protein: 3, carbs: 20, fat: 5, serving: "55 pieces" },
  { name: "Almonds", category: "Snacks", expiry_days: 365, calories: 164, protein: 6, carbs: 6, fat: 14, serving: "1 oz" },
  { name: "Cashews", category: "Snacks", expiry_days: 365, calories: 157, protein: 5, carbs: 9, fat: 12, serving: "1 oz" },
  { name: "Peanuts", category: "Snacks", expiry_days: 365, calories: 166, protein: 7, carbs: 6, fat: 14, serving: "1 oz" },
  { name: "Walnuts", category: "Snacks", expiry_days: 365, calories: 185, protein: 4, carbs: 4, fat: 18, serving: "1 oz" },
  { name: "Pecans", category: "Snacks", expiry_days: 365, calories: 196, protein: 2.6, carbs: 4, fat: 20, serving: "1 oz" },
  { name: "Pistachios", category: "Snacks", expiry_days: 365, calories: 159, protein: 6, carbs: 8, fat: 13, serving: "1 oz" },
  { name: "Mixed Nuts", category: "Snacks", expiry_days: 365, calories: 173, protein: 5, carbs: 8, fat: 16, serving: "1 oz" },
  { name: "Trail Mix", category: "Snacks", expiry_days: 180, calories: 173, protein: 5, carbs: 19, fat: 10, serving: "1 oz" },
  { name: "Popcorn", category: "Snacks", expiry_days: 30, calories: 93, protein: 3, carbs: 19, fat: 1.2, serving: "3 cups popped" },
  { name: "Butter Popcorn", category: "Snacks", expiry_days: 30, calories: 130, protein: 2, carbs: 16, fat: 6, serving: "3 cups popped" },
  { name: "Pretzels", category: "Snacks", expiry_days: 90, calories: 108, protein: 2.6, carbs: 22, fat: 1, serving: "1 oz" },
  { name: "Granola Bar", category: "Snacks", expiry_days: 180, calories: 193, protein: 4, carbs: 28, fat: 7, serving: "1 bar" },
  { name: "Protein Bar", category: "Snacks", expiry_days: 365, calories: 230, protein: 20, carbs: 25, fat: 7, serving: "1 bar" },
  { name: "Energy Bar", category: "Snacks", expiry_days: 365, calories: 250, protein: 10, carbs: 38, fat: 6, serving: "1 bar" },
  { name: "Raisins", category: "Snacks", expiry_days: 180, calories: 130, protein: 1.5, carbs: 34, fat: 0.2, serving: "1/4 cup" },
  { name: "Dried Cranberries", category: "Snacks", expiry_days: 180, calories: 130, protein: 0, carbs: 33, fat: 0.5, serving: "1/4 cup" },
  { name: "Dried Apricots", category: "Snacks", expiry_days: 180, calories: 78, protein: 1.1, carbs: 20, fat: 0.2, serving: "1/4 cup" },
  { name: "Beef Jerky", category: "Snacks", expiry_days: 365, calories: 116, protein: 9.4, carbs: 3.1, fat: 7.3, serving: "1 oz" },
  { name: "Cheese Sticks", category: "Snacks", expiry_days: 21, calories: 80, protein: 7, carbs: 1, fat: 6, serving: "1 stick" },
  { name: "Fruit Snacks", category: "Snacks", expiry_days: 365, calories: 80, protein: 0, carbs: 21, fat: 0, serving: "1 pouch" },
  { name: "Rice Cakes Plain", category: "Snacks", expiry_days: 180, calories: 35, protein: 0.7, carbs: 7, fat: 0.3, serving: "1 cake" },
  { name: "Milk Chocolate Bar", category: "Snacks", expiry_days: 365, calories: 235, protein: 3.4, carbs: 26, fat: 13, serving: "1.5 oz" },
  { name: "Dark Chocolate Bar", category: "Snacks", expiry_days: 365, calories: 170, protein: 2, carbs: 13, fat: 12, serving: "1 oz" },
  { name: "Gummy Bears", category: "Snacks", expiry_days: 365, calories: 140, protein: 3, carbs: 34, fat: 0, serving: "17 pieces" },
  { name: "Sour Gummy Worms", category: "Snacks", expiry_days: 365, calories: 130, protein: 1, carbs: 32, fat: 0, serving: "1 oz" },
  { name: "Oreo Cookies", category: "Snacks", expiry_days: 180, calories: 160, protein: 1, carbs: 25, fat: 7, serving: "3 cookies" },
  { name: "Chips Ahoy Cookies", category: "Snacks", expiry_days: 180, calories: 160, protein: 2, carbs: 22, fat: 8, serving: "3 cookies" },
  { name: "Fig Newtons", category: "Snacks", expiry_days: 180, calories: 110, protein: 1, carbs: 22, fat: 2.5, serving: "2 cookies" },
  { name: "Peanut Butter Cups", category: "Snacks", expiry_days: 365, calories: 210, protein: 5, carbs: 24, fat: 12, serving: "2 cups" },
  { name: "Sunflower Seeds", category: "Snacks", expiry_days: 365, calories: 165, protein: 5.5, carbs: 7, fat: 14, serving: "1 oz" },
  { name: "Pumpkin Seeds", category: "Snacks", expiry_days: 365, calories: 158, protein: 8, carbs: 3, fat: 14, serving: "1 oz" },
  { name: "Macadamia Nuts", category: "Snacks", expiry_days: 365, calories: 204, protein: 2.2, carbs: 4, fat: 21, serving: "1 oz" },
  { name: "Brazil Nuts", category: "Snacks", expiry_days: 365, calories: 187, protein: 4.1, carbs: 3.5, fat: 19, serving: "1 oz" },
  { name: "Hazelnuts", category: "Snacks", expiry_days: 365, calories: 178, protein: 4.2, carbs: 4.7, fat: 17, serving: "1 oz" },
  { name: "Dried Mango", category: "Snacks", expiry_days: 180, calories: 100, protein: 0, carbs: 26, fat: 0, serving: "1/4 cup" },
  { name: "Sesame Sticks", category: "Snacks", expiry_days: 90, calories: 153, protein: 3, carbs: 15, fat: 9, serving: "1 oz" },
  { name: "Corn Nuts", category: "Snacks", expiry_days: 90, calories: 130, protein: 2, carbs: 20, fat: 5, serving: "1 oz" },
  { name: "Snap Pea Crisps", category: "Snacks", expiry_days: 90, calories: 110, protein: 3, carbs: 18, fat: 3, serving: "1 oz" },

  // ─── DELI ─────────────────────────────────────────────────────────────────────
  { name: "Sliced Turkey Breast", category: "Deli", expiry_days: 5, calories: 60, protein: 11, carbs: 1, fat: 1, serving: "2 oz" },
  { name: "Sliced Ham", category: "Deli", expiry_days: 5, calories: 70, protein: 10, carbs: 2, fat: 2.5, serving: "2 oz" },
  { name: "Sliced Roast Beef", category: "Deli", expiry_days: 5, calories: 70, protein: 11, carbs: 0.5, fat: 2.5, serving: "2 oz" },
  { name: "Salami", category: "Deli", expiry_days: 14, calories: 110, protein: 6, carbs: 0.8, fat: 9, serving: "1 oz" },
  { name: "Pepperoni", category: "Deli", expiry_days: 14, calories: 138, protein: 5.7, carbs: 0.8, fat: 12, serving: "1 oz" },
  { name: "Prosciutto", category: "Deli", expiry_days: 7, calories: 70, protein: 10, carbs: 0, fat: 3, serving: "1 oz" },
  { name: "Pastrami", category: "Deli", expiry_days: 5, calories: 99, protein: 14, carbs: 1, fat: 4, serving: "2 oz" },
  { name: "Bologna", category: "Deli", expiry_days: 7, calories: 89, protein: 3.3, carbs: 2.6, fat: 8, serving: "1 oz" },
  { name: "Chicken Salad", category: "Deli", expiry_days: 3, calories: 190, protein: 13, carbs: 3, fat: 14, serving: "1/2 cup" },
  { name: "Tuna Salad", category: "Deli", expiry_days: 3, calories: 190, protein: 15, carbs: 5, fat: 12, serving: "1/2 cup" },
  { name: "Egg Salad", category: "Deli", expiry_days: 3, calories: 200, protein: 10, carbs: 2, fat: 17, serving: "1/2 cup" },
  { name: "Chicken Noodle Soup Prepared", category: "Deli", expiry_days: 3, calories: 120, protein: 9, carbs: 14, fat: 3.5, serving: "1 cup" },
  { name: "Tomato Basil Soup", category: "Deli", expiry_days: 5, calories: 90, protein: 2, carbs: 14, fat: 3, serving: "1 cup" },
  { name: "Rotisserie Chicken", category: "Deli", expiry_days: 4, calories: 190, protein: 22, carbs: 0, fat: 11, serving: "3.5 oz" },
  { name: "Coleslaw", category: "Deli", expiry_days: 3, calories: 120, protein: 1, carbs: 12, fat: 8, serving: "1/2 cup" },
  { name: "Potato Salad", category: "Deli", expiry_days: 3, calories: 180, protein: 2.5, carbs: 21, fat: 10, serving: "1/2 cup" },
  { name: "Macaroni Salad", category: "Deli", expiry_days: 3, calories: 200, protein: 3, carbs: 26, fat: 10, serving: "1/2 cup" },
  { name: "Quiche Lorraine Slice", category: "Deli", expiry_days: 3, calories: 360, protein: 12, carbs: 24, fat: 24, serving: "1 slice" },
  { name: "Deli Hummus", category: "Deli", expiry_days: 7, calories: 100, protein: 3, carbs: 9, fat: 6, serving: "1/4 cup" },
  { name: "Liverwurst", category: "Deli", expiry_days: 7, calories: 115, protein: 5, carbs: 1, fat: 10, serving: "1 oz" },
  { name: "Capicola", category: "Deli", expiry_days: 7, calories: 80, protein: 8, carbs: 0, fat: 5, serving: "1 oz" },
  { name: "Mortadella", category: "Deli", expiry_days: 7, calories: 95, protein: 4.5, carbs: 1.5, fat: 8, serving: "1 oz" },
  { name: "Sliced Chicken Breast", category: "Deli", expiry_days: 5, calories: 50, protein: 10, carbs: 1, fat: 0.8, serving: "2 oz" },
  { name: "Pimento Cheese Spread", category: "Deli", expiry_days: 7, calories: 110, protein: 3, carbs: 2, fat: 10, serving: "2 tbsp" },
  { name: "Smoked Turkey", category: "Deli", expiry_days: 7, calories: 65, protein: 11, carbs: 2, fat: 1, serving: "2 oz" },

  // ─── OTHER (overflow items that don't fit neatly above) ────────────────────
  { name: "Tofu Firm", category: "Other", expiry_days: 5, calories: 70, protein: 8, carbs: 2, fat: 3, serving: "3 oz" },
  { name: "Tofu Silken", category: "Other", expiry_days: 5, calories: 45, protein: 4.8, carbs: 1.5, fat: 2, serving: "3 oz" },
  { name: "Tempeh", category: "Other", expiry_days: 7, calories: 162, protein: 15, carbs: 9, fat: 9, serving: "3 oz" },
  { name: "Seitan", category: "Other", expiry_days: 5, calories: 90, protein: 18, carbs: 3, fat: 1, serving: "3 oz" },
  { name: "Edamame Shelled", category: "Other", expiry_days: 5, calories: 188, protein: 16, carbs: 14, fat: 8, serving: "1 cup" },
  { name: "Black Beans", category: "Other", expiry_days: 7, calories: 227, protein: 15, carbs: 41, fat: 0.9, serving: "1 cup cooked" },
  { name: "Chickpeas", category: "Other", expiry_days: 7, calories: 269, protein: 15, carbs: 45, fat: 4, serving: "1 cup cooked" },
  { name: "Lentils", category: "Other", expiry_days: 7, calories: 230, protein: 18, carbs: 40, fat: 0.8, serving: "1 cup cooked" },
  { name: "Kidney Beans", category: "Other", expiry_days: 7, calories: 225, protein: 15, carbs: 40, fat: 0.9, serving: "1 cup cooked" },
  { name: "Pinto Beans", category: "Other", expiry_days: 7, calories: 245, protein: 15, carbs: 45, fat: 1.1, serving: "1 cup cooked" },
  { name: "Refried Beans", category: "Other", expiry_days: 7, calories: 237, protein: 14, carbs: 39, fat: 3, serving: "1 cup" },
  { name: "Canned Tomatoes", category: "Other", expiry_days: 730, calories: 41, protein: 2, carbs: 10, fat: 0.3, serving: "1 cup" },
  { name: "Tomato Paste", category: "Other", expiry_days: 7, calories: 54, protein: 2.8, carbs: 13, fat: 0.4, serving: "2 tbsp" },
  { name: "Coconut Cream", category: "Other", expiry_days: 7, calories: 200, protein: 2, carbs: 6, fat: 20, serving: "2 tbsp" },
  { name: "Vegetable Broth", category: "Other", expiry_days: 7, calories: 15, protein: 0.5, carbs: 3, fat: 0, serving: "1 cup" },
  { name: "Chicken Broth", category: "Other", expiry_days: 7, calories: 15, protein: 1, carbs: 2, fat: 0.5, serving: "1 cup" },
  { name: "Beef Broth", category: "Other", expiry_days: 7, calories: 17, protein: 2.7, carbs: 0.1, fat: 0.5, serving: "1 cup" },
  { name: "Miso Paste", category: "Other", expiry_days: 90, calories: 34, protein: 2.2, carbs: 5, fat: 1, serving: "1 tbsp" },
  { name: "Kimchi", category: "Other", expiry_days: 90, calories: 23, protein: 1.7, carbs: 4, fat: 0.5, serving: "1/2 cup" },
  { name: "Sauerkraut", category: "Other", expiry_days: 90, calories: 27, protein: 1.3, carbs: 6, fat: 0.2, serving: "1/2 cup" },
  { name: "Pickle Spears", category: "Other", expiry_days: 180, calories: 4, protein: 0.2, carbs: 0.8, fat: 0, serving: "1 spear" },
  { name: "Dill Pickles", category: "Other", expiry_days: 180, calories: 11, protein: 0.4, carbs: 2.6, fat: 0.2, serving: "1 medium" },
  { name: "Sun Dried Tomatoes", category: "Other", expiry_days: 30, calories: 139, protein: 7.6, carbs: 30, fat: 1.5, serving: "1/4 cup" },
  { name: "Artichoke Hearts Canned", category: "Other", expiry_days: 730, calories: 45, protein: 3, carbs: 9, fat: 0.2, serving: "1/2 cup" },
  { name: "Roasted Red Peppers", category: "Other", expiry_days: 14, calories: 15, protein: 0.7, carbs: 3, fat: 0, serving: "1 oz" },
  { name: "Coconut Milk Canned", category: "Other", expiry_days: 730, calories: 445, protein: 4.6, carbs: 6, fat: 48, serving: "1 cup" },
  { name: "Almond Flour", category: "Other", expiry_days: 180, calories: 160, protein: 6, carbs: 6, fat: 14, serving: "1/4 cup" },
  { name: "Chia Seeds", category: "Other", expiry_days: 730, calories: 138, protein: 4.7, carbs: 12, fat: 8.7, serving: "2 tbsp" },
  { name: "Flaxseeds", category: "Other", expiry_days: 365, calories: 74, protein: 2.6, carbs: 4, fat: 6, serving: "1 tbsp" },
  { name: "Hemp Seeds", category: "Other", expiry_days: 365, calories: 166, protein: 9.5, carbs: 2.6, fat: 14.6, serving: "3 tbsp" },
  { name: "Nutritional Yeast", category: "Other", expiry_days: 730, calories: 45, protein: 8, carbs: 5, fat: 0.5, serving: "2 tbsp" },
  { name: "Protein Powder Whey", category: "Other", expiry_days: 730, calories: 120, protein: 25, carbs: 3, fat: 1.5, serving: "1 scoop" },
  { name: "Protein Powder Plant", category: "Other", expiry_days: 730, calories: 120, protein: 22, carbs: 5, fat: 3, serving: "1 scoop" },
  { name: "Greek Salad Kit", category: "Other", expiry_days: 5, calories: 150, protein: 3, carbs: 8, fat: 11, serving: "1.5 cups" },
  { name: "Caesar Salad Kit", category: "Other", expiry_days: 5, calories: 180, protein: 4, carbs: 11, fat: 14, serving: "1.5 cups" },
  { name: "Canned Corn", category: "Other", expiry_days: 730, calories: 66, protein: 2, carbs: 15, fat: 0.8, serving: "1/2 cup" },
  { name: "Canned Green Beans", category: "Other", expiry_days: 730, calories: 20, protein: 1, carbs: 4.5, fat: 0.1, serving: "1/2 cup" },
  { name: "Canned Chickpeas", category: "Other", expiry_days: 730, calories: 269, protein: 15, carbs: 45, fat: 4, serving: "1 cup" },
  { name: "Canned Black Beans", category: "Other", expiry_days: 730, calories: 218, protein: 15, carbs: 40, fat: 0.7, serving: "1 cup" },
  { name: "Butter Lettuce", category: "Produce", expiry_days: 5, calories: 7, protein: 0.7, carbs: 1.2, fat: 0.1, serving: "1 cup" },
  { name: "Broccolini", category: "Produce", expiry_days: 5, calories: 37, protein: 3.5, carbs: 6, fat: 0.4, serving: "1 cup" },
  { name: "Whole Milk Ricotta", category: "Dairy", expiry_days: 7, calories: 216, protein: 14, carbs: 4, fat: 16, serving: "1/2 cup" },
  { name: "Sliced Pepperoni", category: "Deli", expiry_days: 14, calories: 138, protein: 5.7, carbs: 0.8, fat: 12, serving: "1 oz" },
  { name: "Frozen Hash Browns", category: "Frozen", expiry_days: 270, calories: 70, protein: 1, carbs: 16, fat: 0, serving: "1 patty" },
  { name: "Pistachios Shelled", category: "Snacks", expiry_days: 365, calories: 159, protein: 6, carbs: 8, fat: 13, serving: "1 oz" },
  { name: "Lentil Soup Prepared", category: "Deli", expiry_days: 5, calories: 180, protein: 11, carbs: 28, fat: 3, serving: "1 cup" },
  { name: "Honeycrisp Apple", category: "Produce", expiry_days: 35, calories: 80, protein: 0.4, carbs: 22, fat: 0.3, serving: "1 medium" },
  { name: "Beef Bone Broth", category: "Other", expiry_days: 7, calories: 40, protein: 9, carbs: 0, fat: 1, serving: "1 cup" },
  { name: "Oat Milk Barista", category: "Dairy", expiry_days: 10, calories: 130, protein: 4, carbs: 18, fat: 5, serving: "1 cup" },
];
